package ro.cst.tsearch.country;

import java.util.HashMap;

/*
 * Country list
 */
public class Countries {


	public final static HashMap<String, String> COUNTRY_LIST = new HashMap<String, String>();

	static {
		COUNTRY_LIST.put("AF", "AFGHANISTAN");
		COUNTRY_LIST.put("AX", "ÅLAND ISLANDS");
		COUNTRY_LIST.put("AL", "ALBANIA");
		COUNTRY_LIST.put("DZ", "ALGERIA");
		COUNTRY_LIST.put("AS", "AMERICAN SAMOA");
		COUNTRY_LIST.put("AD", "ANDORRA");
		COUNTRY_LIST.put("AO", "ANGOLA");
		COUNTRY_LIST.put("AI", "ANGUILLA");
		COUNTRY_LIST.put("AQ", "ANTARCTICA");
		COUNTRY_LIST.put("AG", "ANTIGUA AND BARBUDA");
		COUNTRY_LIST.put("AR", "ARGENTINA");
		COUNTRY_LIST.put("AM", "ARMENIA");
		COUNTRY_LIST.put("AW", "ARUBA");
		COUNTRY_LIST.put("AU", "AUSTRALIA");
		COUNTRY_LIST.put("AT", "AUSTRIA");
		COUNTRY_LIST.put("AZ", "AZERBAIJAN");
		COUNTRY_LIST.put("BS", "BAHAMAS");
		COUNTRY_LIST.put("BH", "BAHRAIN");
		COUNTRY_LIST.put("BD", "BANGLADESH");
		COUNTRY_LIST.put("BB", "BARBADOS");
		COUNTRY_LIST.put("BY", "BELARUS");
		COUNTRY_LIST.put("BE", "BELGIUM");
		COUNTRY_LIST.put("BZ", "BELIZE");
		COUNTRY_LIST.put("BJ", "BENIN");
		COUNTRY_LIST.put("BM", "BERMUDA");
		COUNTRY_LIST.put("BT", "BHUTAN");
		COUNTRY_LIST.put("BO", "BOLIVIA");
		COUNTRY_LIST.put("BA", "BOSNIA AND HERZEGOVINA");
		COUNTRY_LIST.put("BW", "BOTSWANA");
		COUNTRY_LIST.put("BV", "BOUVET ISLAND");
		COUNTRY_LIST.put("BR", "BRAZIL");
		COUNTRY_LIST.put("IO", "BRITISH INDIAN OCEAN TERRITORY");
		COUNTRY_LIST.put("BN", "BRUNEI DARUSSALAM");
		COUNTRY_LIST.put("BG", "BULGARIA");
		COUNTRY_LIST.put("BF", "BURKINA FASO");
		COUNTRY_LIST.put("BI", "BURUNDI");
		COUNTRY_LIST.put("KH", "CAMBODIA");
		COUNTRY_LIST.put("CM", "CAMEROON");
		COUNTRY_LIST.put("CA", "CANADA");
		COUNTRY_LIST.put("CV", "CAPE VERDE");
		COUNTRY_LIST.put("KY", "CAYMAN ISLANDS");
		COUNTRY_LIST.put("CF", "CENTRAL AFRICAN REPUBLIC");
		COUNTRY_LIST.put("TD", "CHAD");
		COUNTRY_LIST.put("CL", "CHILE");
		COUNTRY_LIST.put("CN", "CHINA");
		COUNTRY_LIST.put("CX", "CHRISTMAS ISLAND");
		COUNTRY_LIST.put("CC", "COCOS (KEELING) ISLANDS");
		COUNTRY_LIST.put("CO", "COLOMBIA");
		COUNTRY_LIST.put("KM", "COMOROS");
		COUNTRY_LIST.put("CG", "CONGO");
		COUNTRY_LIST.put("CD", "CONGO, THE DEMOCRATIC REPUBLIC OF THE");
		COUNTRY_LIST.put("CK", "COOK ISLANDS");
		COUNTRY_LIST.put("CR", "COSTA RICA");
		COUNTRY_LIST.put("CI", "CÔTE D'IVOIRE");
		COUNTRY_LIST.put("HR", "CROATIA");
		COUNTRY_LIST.put("CU", "CUBA");
		COUNTRY_LIST.put("CY", "CYPRUS");
		COUNTRY_LIST.put("CZ", "CZECH REPUBLIC");
		COUNTRY_LIST.put("DK", "DENMARK");
		COUNTRY_LIST.put("DJ", "DJIBOUTI");
		COUNTRY_LIST.put("DM", "DOMINICA");
		COUNTRY_LIST.put("DO", "DOMINICAN REPUBLIC");
		COUNTRY_LIST.put("EN", "ENGLAND");
		COUNTRY_LIST.put("EC", "ECUADOR");
		COUNTRY_LIST.put("EG", "EGYPT");
		COUNTRY_LIST.put("SV", "EL SALVADOR");
		COUNTRY_LIST.put("GQ", "EQUATORIAL GUINEA");
		COUNTRY_LIST.put("ER", "ERITREA");
		COUNTRY_LIST.put("EE", "ESTONIA");
		COUNTRY_LIST.put("ET", "ETHIOPIA");
		COUNTRY_LIST.put("FK", "FALKLAND ISLANDS (MALVINAS)");
		COUNTRY_LIST.put("FO", "FAROE ISLANDS");
		COUNTRY_LIST.put("FJ", "FIJI");
		COUNTRY_LIST.put("FI", "FINLAND");
		COUNTRY_LIST.put("FR", "FRANCE");
		COUNTRY_LIST.put("GF", "FRENCH GUIANA");
		COUNTRY_LIST.put("PF", "FRENCH POLYNESIA");
		COUNTRY_LIST.put("TF", "FRENCH SOUTHERN TERRITORIES");
		COUNTRY_LIST.put("GA", "GABON");
		COUNTRY_LIST.put("GM", "GAMBIA");
		COUNTRY_LIST.put("GE", "GEORGIA");
		COUNTRY_LIST.put("DE", "GERMANY");
		COUNTRY_LIST.put("GH", "GHANA");
		COUNTRY_LIST.put("GI", "GIBRALTAR");
		COUNTRY_LIST.put("GR", "GREECE");
		COUNTRY_LIST.put("GL", "GREENLAND");
		COUNTRY_LIST.put("GD", "GRENADA");
		COUNTRY_LIST.put("GP", "GUADELOUPE");
		COUNTRY_LIST.put("GU", "GUAM");
		COUNTRY_LIST.put("GT", "GUATEMALA");
		COUNTRY_LIST.put("GG", "GUERNSEY");
		COUNTRY_LIST.put("GN", "GUINEA");
		COUNTRY_LIST.put("GW", "GUINEA-BISSAU");
		COUNTRY_LIST.put("GY", "GUYANA");
		COUNTRY_LIST.put("HT", "HAITI");
		COUNTRY_LIST.put("HM", "HEARD ISLAND AND MCDONALD ISLANDS");
		COUNTRY_LIST.put("VA", "HOLY SEE (VATICAN CITY STATE)");
		COUNTRY_LIST.put("HN", "HONDURAS");
		COUNTRY_LIST.put("HK", "HONG KONG");
		COUNTRY_LIST.put("HU", "HUNGARY");
		COUNTRY_LIST.put("IS", "ICELAND");
		COUNTRY_LIST.put("IN", "INDIA");
		COUNTRY_LIST.put("ID", "INDONESIA");
		COUNTRY_LIST.put("IR", "IRAN, ISLAMIC REPUBLIC OF");
		COUNTRY_LIST.put("IQ", "IRAQ");
		COUNTRY_LIST.put("IE", "IRELAND");
		COUNTRY_LIST.put("IM", "ISLE OF MAN");
		COUNTRY_LIST.put("IL", "ISRAEL");
		COUNTRY_LIST.put("IT", "ITALY");
		COUNTRY_LIST.put("JM", "JAMAICA");
		COUNTRY_LIST.put("JP", "JAPAN");
		COUNTRY_LIST.put("JE", "JERSEY");
		COUNTRY_LIST.put("JO", "JORDAN");
		COUNTRY_LIST.put("KZ", "KAZAKHSTAN");
		COUNTRY_LIST.put("KE", "KENYA");
		COUNTRY_LIST.put("KI", "KIRIBATI");
		COUNTRY_LIST.put("KP", "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF");
		COUNTRY_LIST.put("KR", "KOREA, REPUBLIC OF");
		COUNTRY_LIST.put("KW", "KUWAIT");
		COUNTRY_LIST.put("KG", "KYRGYZSTAN");
		COUNTRY_LIST.put("LA", "LAO PEOPLE'S DEMOCRATIC REPUBLIC");
		COUNTRY_LIST.put("LV", "LATVIA");
		COUNTRY_LIST.put("LB", "LEBANON");
		COUNTRY_LIST.put("LS", "LESOTHO");
		COUNTRY_LIST.put("LR", "LIBERIA");
		COUNTRY_LIST.put("LY", "LIBYAN ARAB JAMAHIRIYA");
		COUNTRY_LIST.put("LI", "LIECHTENSTEIN");
		COUNTRY_LIST.put("LT", "LITHUANIA");
		COUNTRY_LIST.put("LU", "LUXEMBOURG");
		COUNTRY_LIST.put("MO", "MACAO");
		COUNTRY_LIST.put("MK", "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF");
		COUNTRY_LIST.put("MG", "MADAGASCAR");
		COUNTRY_LIST.put("MW", "MALAWI");
		COUNTRY_LIST.put("MY", "MALAYSIA");
		COUNTRY_LIST.put("MV", "MALDIVES");
		COUNTRY_LIST.put("ML", "MALI");
		COUNTRY_LIST.put("MT", "MALTA");
		COUNTRY_LIST.put("MH", "MARSHALL ISLANDS");
		COUNTRY_LIST.put("MQ", "MARTINIQUE");
		COUNTRY_LIST.put("MR", "MAURITANIA");
		COUNTRY_LIST.put("MU", "MAURITIUS");
		COUNTRY_LIST.put("YT", "MAYOTTE");
		COUNTRY_LIST.put("MX", "MEXICO");
		COUNTRY_LIST.put("FM", "MICRONESIA, FEDERATED STATES OF");
		COUNTRY_LIST.put("MD", "MOLDOVA");
		COUNTRY_LIST.put("MC", "MONACO");
		COUNTRY_LIST.put("MN", "MONGOLIA");
		COUNTRY_LIST.put("ME", "MONTENEGRO");
		COUNTRY_LIST.put("MS", "MONTSERRAT");
		COUNTRY_LIST.put("MA", "MOROCCO");
		COUNTRY_LIST.put("MZ", "MOZAMBIQUE");
		COUNTRY_LIST.put("MM", "MYANMAR");
		COUNTRY_LIST.put("NA", "NAMIBIA");
		COUNTRY_LIST.put("NR", "NAURU");
		COUNTRY_LIST.put("NP", "NEPAL");
		COUNTRY_LIST.put("NL", "NETHERLANDS");
		COUNTRY_LIST.put("AN", "NETHERLANDS ANTILLES");
		COUNTRY_LIST.put("NC", "NEW CALEDONIA");
		COUNTRY_LIST.put("NZ", "NEW ZEALAND");
		COUNTRY_LIST.put("NI", "NICARAGUA");
		COUNTRY_LIST.put("NE", "NIGER");
		COUNTRY_LIST.put("NG", "NIGERIA");
		COUNTRY_LIST.put("NU", "NIUE");
		COUNTRY_LIST.put("NF", "NORFOLK ISLAND");
		COUNTRY_LIST.put("MP", "NORTHERN MARIANA ISLANDS");
		COUNTRY_LIST.put("NO", "NORWAY");
		COUNTRY_LIST.put("OM", "OMAN");
		COUNTRY_LIST.put("PK", "PAKISTAN");
		COUNTRY_LIST.put("PW", "PALAU");
		COUNTRY_LIST.put("PS", "PALESTINIAN TERRITORY, OCCUPIED");
		COUNTRY_LIST.put("PA", "PANAMA");
		COUNTRY_LIST.put("PG", "PAPUA NEW GUINEA");
		COUNTRY_LIST.put("PY", "PARAGUAY");
		COUNTRY_LIST.put("PE", "PERU");
		COUNTRY_LIST.put("PH", "PHILIPPINES");
		COUNTRY_LIST.put("PN", "PITCAIRN");
		COUNTRY_LIST.put("PL", "POLAND");
		COUNTRY_LIST.put("PT", "PORTUGAL");
		COUNTRY_LIST.put("PR", "PUERTO RICO");
		COUNTRY_LIST.put("QA", "QATAR");
		COUNTRY_LIST.put("RE", "RÉUNION");
		COUNTRY_LIST.put("RO", "ROMANIA");
		COUNTRY_LIST.put("RU", "RUSSIAN FEDERATION");
		COUNTRY_LIST.put("RW", "RWANDA");
		COUNTRY_LIST.put("BL", "SAINT BARTHÉLEMY");
		COUNTRY_LIST.put("SH", "SAINT HELENA");
		COUNTRY_LIST.put("KN", "SAINT KITTS AND NEVIS");
		COUNTRY_LIST.put("LC", "SAINT LUCIA");
		COUNTRY_LIST.put("MF", "SAINT MARTIN");
		COUNTRY_LIST.put("PM", "SAINT PIERRE AND MIQUELON");
		COUNTRY_LIST.put("VC", "SAINT VINCENT AND THE GRENADINES");
		COUNTRY_LIST.put("WS", "SAMOA");
		COUNTRY_LIST.put("SM", "SAN MARINO");
		COUNTRY_LIST.put("ST", "SAO TOME AND PRINCIPE");
		COUNTRY_LIST.put("SA", "SAUDI ARABIA");
		COUNTRY_LIST.put("SN", "SENEGAL");
		COUNTRY_LIST.put("RS", "SERBIA");
		COUNTRY_LIST.put("SC", "SEYCHELLES");
		COUNTRY_LIST.put("SL", "SIERRA LEONE");
		COUNTRY_LIST.put("SG", "SINGAPORE");
		COUNTRY_LIST.put("SK", "SLOVAKIA");
		COUNTRY_LIST.put("SI", "SLOVENIA");
		COUNTRY_LIST.put("SB", "SOLOMON ISLANDS");
		COUNTRY_LIST.put("SO", "SOMALIA");
		COUNTRY_LIST.put("ZA", "SOUTH AFRICA");
		COUNTRY_LIST.put("GS", "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS ");
		COUNTRY_LIST.put("ES", "SPAIN");
		COUNTRY_LIST.put("LK", "SRI LANKA");
		COUNTRY_LIST.put("SD", "SUDAN");
		COUNTRY_LIST.put("SR", "SURINAME");
		COUNTRY_LIST.put("SJ", "SVALBARD AND JAN MAYEN");
		COUNTRY_LIST.put("SZ", "SWAZILAND");
		COUNTRY_LIST.put("SE", "SWEDEN");
		COUNTRY_LIST.put("CH", "SWITZERLAND");
		COUNTRY_LIST.put("SY", "SYRIAN ARAB REPUBLIC");
		COUNTRY_LIST.put("TW", "TAIWAN, PROVINCE OF CHINA");
		COUNTRY_LIST.put("TJ", "TAJIKISTAN");
		COUNTRY_LIST.put("TZ", "TANZANIA, UNITED REPUBLIC OF");
		COUNTRY_LIST.put("TH", "THAILAND");
		COUNTRY_LIST.put("TL", "TIMOR-LESTE");
		COUNTRY_LIST.put("TG", "TOGO");
		COUNTRY_LIST.put("TK", "TOKELAU");
		COUNTRY_LIST.put("TO", "TONGA");
		COUNTRY_LIST.put("TT", "TRINIDAD AND TOBAGO");
		COUNTRY_LIST.put("TN", "TUNISIA");
		COUNTRY_LIST.put("TR", "TURKEY");
		COUNTRY_LIST.put("TM", "TURKMENISTAN");
		COUNTRY_LIST.put("TC", "TURKS AND CAICOS ISLANDS");
		COUNTRY_LIST.put("TV", "TUVALU");
		COUNTRY_LIST.put("UG", "UGANDA");
		COUNTRY_LIST.put("UA", "UKRAINE");
		COUNTRY_LIST.put("AE", "UNITED ARAB EMIRATES");
		COUNTRY_LIST.put("GB", "UNITED KINGDOM");
		COUNTRY_LIST.put("US", "UNITED STATES");
		COUNTRY_LIST.put("UM", "UNITED STATES MINOR OUTLYING ISLANDS");
		COUNTRY_LIST.put("UY", "URUGUAY");
		COUNTRY_LIST.put("UZ", "UZBEKISTAN");
		COUNTRY_LIST.put("VU", "VANUATU");
		COUNTRY_LIST.put("VA", "VATICAN CITY STATE");
		COUNTRY_LIST.put("VE", "VENEZUELA");
		COUNTRY_LIST.put("VN", "VIETNAM");
		COUNTRY_LIST.put("VG", "VIRGIN ISLANDS, BRITISH");
		COUNTRY_LIST.put("VI", "VIRGIN ISLANDS, U.S.");
		COUNTRY_LIST.put("WF", "WALLIS AND FUTUNA");
		COUNTRY_LIST.put("EH", "WESTERN SAHARA");
		COUNTRY_LIST.put("YE", "YEMEN");
		COUNTRY_LIST.put("ZM", "ZAMBIA");
		COUNTRY_LIST.put("ZW", "ZIMBABWE");
	}
	
	
	/**return true if string is key or value in CountryList*/
	public static boolean isCountry(String c){
		if (COUNTRY_LIST.containsKey(c)
			|| COUNTRY_LIST.containsValue(c)){
			return true;
		}
		return false;
	}
	
	/**
	 * Get full name for country name abbreviation<br>
	 * Will return empty string if the country code does not exists
	 * @param abr
	 * @return
	 */
	public static String getFullCountry(String abr){
		String c = COUNTRY_LIST.get(abr);
		return (c == null)? "": c;
	}
}

		