package ro.cst.tsearch.servers.types;

public class ILWinnebagoIS extends GenericISI {
	
	public static final long serialVersionUID = 10000000L;
	
	public ILWinnebagoIS(long searchId) {
		super(searchId);
	}

	public ILWinnebagoIS(String rsRequestSolverName, String rsSitePath, String rsServerID, String rsPrmNameLink, long searchId, int mid) {
		super(rsRequestSolverName, rsSitePath, rsServerID, rsPrmNameLink, searchId, mid);
	}

	@Override
	protected void loadSpecialFields() {
		pinNote = "(eg: 0419278007)";
	
		SCHOOL_SELECT = 
			"<select tabindex=\"110\" id=\"ddlSchool\" multiple=\"multiple\" size=\"4\" name=\"ddlSchool\">" +
				"<option value=\"\"> No Selection </option>" +
				"<option value=\"126            \">ALSIP-HAZLGRN-OAKLAWN</option>" +
				"<option value=\"145            \">ARBOR PARK</option>" +
				"<option value=\"25             \">ARLINGTON HEIGHTS</option>" +
				"<option value=\"125            \">ATWOOD HEIGHTS</option>" +
				"<option value=\"37             \">AVOCA</option>" +
				"<option value=\"220            \">BARRINGTON C U</option>" +
				"<option value=\"88             \">BELLWOOD</option>" +
				"<option value=\"87             \">BERKELY</option>" +
				"<option value=\"98             \">BERWYN NORTH</option>" +
				"<option value=\"100            \">BERWYN SOUTH</option>" +
				"<option value=\"130            \">BLUE ISLAND</option>" +
				"<option value=\"95             \">BROOKFIELD</option>" +
				"<option value=\"167            \">BROOKWOOD</option>" +
				"<option value=\"111            \">BURBANK</option>" +
				"<option value=\"155            \">CALUMET CITY</option>" +
				"<option value=\"132            \">CALUMET PUBLIC</option>" +
				"<option value=\"110            \">CENTRAL STICKNEY</option>" +
				"<option value=\"170            \">CHICAGO HEIGHTS</option>" +
				"<option value=\"99             \">CICERO</option>" +
				"<option value=\"168            \">COMM CONS</option>" +
				"<option value=\"59             \">COMM CONS</option>" +
				"<option value=\"160            \">COUNTRY CLUB HILLS</option>" +
				"<option value=\"62             \">DES PLAINES C C</option>" +
				"<option value=\"148            \">DOLTON</option>" +
				"<option value=\"149            \">DOLTON</option>" +
				"<option value=\"300            \">DUNDEE COMM UNIT</option>" +
				"<option value=\"169            \">EAST CHICAGO HEIGHTS</option>" +
				"<option value=\"63             \">EAST MAINE</option>" +
				"<option value=\"73             \">EAST PRAIRIE</option>" +
				"<option value=\"159            \">ELEM SCHOOL DISTRICT</option>" +
				"<option value=\"401            \">ELMWOOD PARK C U</option>" +
				"<option value=\"65             \">EVANSTON C C</option>" +
				"<option value=\"124            \">EVERGREEN PK ELEM</option>" +
				"<option value=\"161            \">FLOSSMOOR</option>" +
				"<option value=\"91             \">FOREST PARK</option>" +
				"<option value=\"142            \">FOREST RIDGE</option>" +
				"<option value=\"84             \">FRANKLIN PARK</option>" +
				"<option value=\"133            \">GEN GEO PATTON</option>" +
				"<option value=\"35             \">GLENCOE</option>" +
				"<option value=\"34             \">GLENVIEW C C</option>" +
				"<option value=\"67             \">GOLF ELEM</option>" +
				"<option value=\"152            \">HARVEY</option>" +
				"<option value=\"93             \">HILLSIDE</option>" +
				"<option value=\"181            \">HINSDALE C C</option>" +
				"<option value=\"153            \">HOMEWOOD</option>" +
				"<option value=\"157            \">HOOVER-SCHRUM MEMORIAL</option>" +
				"<option value=\"109            \">INDIAN SPRINGS</option>" +
				"<option value=\"38             \">KENILWORTH</option>" +
				"<option value=\"140            \">KIRBY</option>" +
				"<option value=\"94             \">KOMAREK</option>" +
				"<option value=\"102            \">LA GRANGE</option>" +
				"<option value=\"105            \">LAGRANGE</option>" +
				"<option value=\"106            \">LAGRANGE HIGHLANDS</option>" +
				"<option value=\"158            \">LANSING</option>" +
				"<option value=\"113            \">LEMONT-BROMBEREK</option>" +
				"<option value=\"156            \">LINCOLN ELEM</option>" +
				"<option value=\"74             \">LINCOLNWOOD</option>" +
				"<option value=\"103            \">LYONS</option>" +
				"<option value=\"83             \">MANNHEIM</option>" +
				"<option value=\"162            \">MATTESON ELEM</option>" +
				"<option value=\"89             \">MAYWOOD-MELROSE-BROADVIEW</option>" +
				"<option value=\"70             \">MORTON GROVE</option>" +
				"<option value=\"57             \">MOUNT PROSPECT</option>" +
				"<option value=\"71             \">NILES ELEM</option>" +
				"<option value=\"180            \">NO SCHOOL LISTED</option>" +
				"<option value=\"80             \">NORRIDGE</option>" +
				"<option value=\"117            \">NORTH PALOS</option>" +
				"<option value=\"28             \">NORTHBROOK</option>" +
				"<option value=\"27             \">NORTHBROOK ELEM</option>" +
				"<option value=\"30             \">NORTHBROOK/GLENVIEW</option>" +
				"<option value=\"123            \">OAK LAWN-HOMETOWN</option>" +
				"<option value=\"97             \">OAK PARK ELEM</option>" +
				"<option value=\"135            \">ORLAND</option>" +
				"<option value=\"15             \">PALATINE C C</option>" +
				"<option value=\"118            \">PALOS COMM CONS</option>" +
				"<option value=\"128            \">PALOS HEIGHTS</option>" +
				"<option value=\"163            \">PARK FOREST</option>" +
				"<option value=\"64             \">PARK RIDGE C C</option>" +
				"<option value=\"79             \">PENNOYER</option>" +
				"<option value=\"107            \">PLEASANTDALE</option>" +
				"<option value=\"143            \">POSEN-ROBBINS EL</option>" +
				"<option value=\"144            \">PRAIRIE-HILLS ELEM</option>" +
				"<option value=\"23             \">PROSPECT HEIGHTS</option>" +
				"<option value=\"122            \">RIDGELAND</option>" +
				"<option value=\"85             \">RIVER GROVE</option>" +
				"<option value=\"26             \">RIVER TRAILS</option>" +
				"<option value=\"96             \">RIVERSIDE</option>" +
				"<option value=\"78             \">ROSEMONT ELEM</option>" +
				"<option value=\"172            \">SANDRIDGE</option>" +
				"<option value=\"54             \">SCHAUMBURG C C</option>" +
				"<option value=\"81             \">SCHILLER PARK</option>" +
				"<option value=\"46             \">SCHOOL DISTRICT 46</option>" +
				"<option value=\"68             \">SKOKIE</option>" +
				"<option value=\"69             \">SKOKIE</option>" +
				"<option value=\"72             \">SKOKIE FAIRVIEW</option>" +
				"<option value=\"150            \">SOUTH HOLLAND</option>" +
				"<option value=\"151            \">SOUTH HOLLAND</option>" +
				"<option value=\"194            \">STEGER</option>" +
				"<option value=\"104            \">SUMMIT</option>" +
				"<option value=\"171            \">SUNNYBROOK</option>" +
				"<option value=\"29             \">SUNSET RIDGE</option>" +
				"<option value=\"154            \">THORNTON</option>" +
				"<option value=\"146            \">TINLEY PARK COMM</option>" +
				"<option value=\"86             \">UNION RIDGE</option>" +
				"<option value=\"147            \">W HARVEY-DIXMOOR PUB</option>" +
				"<option value=\"31             \">WEST NORTHFIELD</option>" +
				"<option value=\"92             \">WESTCHESTER</option>" +
				"<option value=\"101            \">WESTERN SPRINGS</option>" +
				"<option value=\"21             \">WHEELING C C</option>" +
				"<option value=\"108            \">WILLOW SPRINGS</option>" +
				"<option value=\"39             \">WILMETTE</option>" +
				"<option value=\"36             \">WINNETKA</option>" +
				"<option value=\"127            \">WORTH</option>" +
		
			"</select>";
		
		ZIP_SELECT = 
			"<select tabindex=\"27\" id=\"ddlZip\" multiple=\"multiple\" size=\"4\" name=\"ddlZip\">" +
				"<option value=\" No Selection \"> No Selection </option>" +
				"<option value=\"02185\">02185</option>" +
				"<option value=\"13224\">13224</option>" +
				"<option value=\"30114\">30114</option>" +
				"<option value=\"34990\">34990</option>" +
				"<option value=\"43413\">43413</option>" +
				"<option value=\"46992\">46992</option>" +
				"<option value=\"50312\">50312</option>" +
				"<option value=\"53005\">53005</option>" +
				"<option value=\"53029\">53029</option>" +
				"<option value=\"53191\">53191</option>" +
				"<option value=\"53511\">53511</option>" +
				"<option value=\"53520\">53520</option>" +
				"<option value=\"53534\">53534</option>" +
				"<option value=\"53546\">53546</option>" +
				"<option value=\"53562\">53562</option>" +
				"<option value=\"54481\">54481</option>" +
				"<option value=\"54501\">54501</option>" +
				"<option value=\"54960\">54960</option>" +
				"<option value=\"60016\">60016</option>" +
				"<option value=\"60047\">60047</option>" +
				"<option value=\"60050\">60050</option>" +
				"<option value=\"60053\">60053</option>" +
				"<option value=\"60067\">60067</option>" +
				"<option value=\"60103\">60103</option>" +
				"<option value=\"60104\">60104</option>" +
				"<option value=\"60146\">60146</option>" +
				"<option value=\"60163\">60163</option>" +
				"<option value=\"60172\">60172</option>" +
				"<option value=\"60175\">60175</option>" +
				"<option value=\"60201\">60201</option>" +
				"<option value=\"60507\">60507</option>" +
				"<option value=\"60516\">60516</option>" +
				"<option value=\"60540\">60540</option>" +
				"<option value=\"60601\">60601</option>" +
				"<option value=\"60602\">60602</option>" +
				"<option value=\"60606\">60606</option>" +
				"<option value=\"60632\">60632</option>" +
				"<option value=\"60690\">60690</option>" +
				"<option value=\"60714\">60714</option>" +
				"<option value=\"60914\">60914</option>" +
				"<option value=\"61003\">61003</option>" +
				"<option value=\"61008\">61008</option>" +
				"<option value=\"61010\">61010</option>" +
				"<option value=\"61011\">61011</option>" +
				"<option value=\"61015\">61015</option>" +
				"<option value=\"61016\">61016</option>" +
				"<option value=\"61019\">61019</option>" +
				"<option value=\"61020\">61020</option>" +
				"<option value=\"61024\">61024</option>" +
				"<option value=\"61032\">61032</option>" +
				"<option value=\"61036\">61036</option>" +
				"<option value=\"61047\">61047</option>" +
				"<option value=\"61052\">61052</option>" +
				"<option value=\"61063\">61063</option>" +
				"<option value=\"61064\">61064</option>" +
				"<option value=\"61065\">61065</option>" +
				"<option value=\"61067\">61067</option>" +
				"<option value=\"61068\">61068</option>" +
				"<option value=\"61072\">61072</option>" +
				"<option value=\"61073\">61073</option>" +
				"<option value=\"61077\">61077</option>" +
				"<option value=\"61078\">61078</option>" +
				"<option value=\"61079\">61079</option>" +
				"<option value=\"61080\">61080</option>" +
				"<option value=\"61084\">61084</option>" +
				"<option value=\"61086\">61086</option>" +
				"<option value=\"61088\">61088</option>" +
				"<option value=\"61101\">61101</option>" +
				"<option value=\"61102\">61102</option>" +
				"<option value=\"61103\">61103</option>" +
				"<option value=\"61104\">61104</option>" +
				"<option value=\"61105\">61105</option>" +
				"<option value=\"61106\">61106</option>" +
				"<option value=\"61107\">61107</option>" +
				"<option value=\"61108\">61108</option>" +
				"<option value=\"61109\">61109</option>" +
				"<option value=\"61110\">61110</option>" +
				"<option value=\"61111\">61111</option>" +
				"<option value=\"61112\">61112</option>" +
				"<option value=\"61114\">61114</option>" +
				"<option value=\"61115\">61115</option>" +
				"<option value=\"61125\">61125</option>" +
				"<option value=\"61132\">61132</option>" +
				"<option value=\"611O8\">611O8</option>" +
				"<option value=\"61702\">61702</option>" +
				"<option value=\"61O19\">61O19</option>" +
				"<option value=\"62537\">62537</option>" +
				"<option value=\"62702\">62702</option>" +
				"<option value=\"63188\">63188</option>" +
				"<option value=\"91101\">91101</option>" +
				"<option value=\"93727\">93727</option>" +
				"<option value=\"95008\">95008</option>" +
				"<option value=\"EY IL\">EY IL</option>" +
			"</select>";
		LAND_USE_SELECT = 
			"<select tabindex=\"92\" id=\"ddlLandUseCodes\" multiple=\"multiple\" size=\"4\" name=\"ddlLandUseCodes\">" +
				"<option value=\"\"> No Selection </option>" +
				"<option value=\"10\">Vacant Rural Prop N Residential Taxable - 10             </option>" +
				"<option value=\"11\">Rural Prop+Imprv N Residential Taxable - 11             </option>" +
				"<option value=\"20\">Vacant Farmland - assd F Farm Taxable - 20             </option>" +
				"<option value=\"21\">Farm+Improve-assd/w/ H&amp;S F Farm Taxable - 21             </option>" +
				"<option value=\"22\">Farm+Improve+Non Farm AV F Commercial Taxable - 22             </option>" +
				"<option value=\"23\">Farm+Imp+H&amp;S- assd/NFarm F Farm Taxable - 23             </option>" +
				"<option value=\"30\">Vacant Residential Land N Residential Taxable - 30             </option>" +
				"<option value=\"31\">Single Family Residence N Residential Taxable - 31             </option>" +
				"<option value=\"32\">Two Family Residence N Residential Taxable - 32             </option>" +
				"<option value=\"33\">Three Family Residence N Residential Taxable - 33             </option>" +
				"<option value=\"34\">Four Family Residence N Residential Taxable - 34             </option>" +
				"<option value=\"35\">Five Family Residence N Residential Taxable - 35             </option>" +
				"<option value=\"36\">Six Family Residence N Residential Taxable - 36             </option>" +
				"<option value=\"37\">Condominium (Residential) N Residential Taxable - 37             </option>" +
				"<option value=\"38\">Res Land+Imprv (no dwell) N Residential Taxable - 38             </option>" +
				"<option value=\"39\">Pref Asd Res(not1/3)10-30 N Residential Taxable - 39             </option>" +
				"<option value=\"40\">Association Owned Prop N Residential Taxable - 40             </option>" +
				"<option value=\"4000\">State Assessed Railroad N State Rail Road State As - 4000           </option>" +
				"<option value=\"41\">Model Home 10-25 N Residential Taxable - 41             </option>" +
				"<option value=\"4500\">State Assessed Railroad N State Rail Road State As - 4500           </option>" +
				"<option value=\"4600\">Pollution Control N Industrial State Assessed - 4600           </option>" +
				"<option value=\"50\">Vac Commercial Res-Land N Commercial Taxable - 50             </option>" +
				"<option value=\"5000\">Locally Assessed Railroad N Local Rail Road Taxabl - 5000           </option>" +
				"<option value=\"51\">Comm Res (6+units)-Imp N Commercial Taxable - 51             </option>" +
				"<option value=\"59\">Pref Asd Com(not1/3)10-30 N Commercial Taxable - 59             </option>" +
				"<option value=\"60\">Vac Comm Business-Land N Commercial Taxable - 60             </option>" +
				"<option value=\"61\">Commercial Business-Impr N Commercial Taxable - 61             </option>" +
				"<option value=\"65\">Commercial with Farm F Commercial Taxable - 65             </option>" +
				"<option value=\"70\">Vac Comm Office-Land N Commercial Taxable - 70             </option>" +
				"<option value=\"71\">Commercial Office-Impr N Commercial Taxable - 71             </option>" +
				"<option value=\"7100\">Coal Assessments N Mineral Taxable - 7100           </option>" +
				"<option value=\"7101\">Developed Coal N Mineral Taxable - 7101           </option>" +
				"<option value=\"72\">Government Building N Commercial Taxable - 72             </option>" +
				"<option value=\"7200\">Oil Leases N Mineral Taxable - 7200           </option>" +
				"<option value=\"73\">Educational Property N Commercial Taxable - 73             </option>" +
				"<option value=\"7300\">Min - Limestone N Mineral Taxable - 7300           </option>" +
				"<option value=\"74\">Religious Property N Commercial Taxable - 74             </option>" +
				"<option value=\"7400\">Min - Sand/Gravel N Mineral Taxable - 7400           </option>" +
				"<option value=\"75\">Social/Charitable/Fratern N Commercial Taxable - 75             </option>" +
				"<option value=\"7500\">Min - Fluorspar N Mineral Taxable - 7500           </option>" +
				"<option value=\"7600\">Min - Miscellaneous N Mineral Taxable - 7600           </option>" +
				"<option value=\"80\">Vacant Industrial Land N Industrial Taxable - 80             </option>" +
				"<option value=\"8011\">Prorated Instant Asmt Rs N Residential Taxable - 8011           </option>" +
				"<option value=\"8031\">Prorated Instant Asmt Rs N Residential Taxable - 8031           </option>" +
				"<option value=\"8034\">Prorated Instant Asmt Rs N Residential Taxable - 8034           </option>" +
				"<option value=\"8037\">Prorated Instant Asmt Rs N Residential Taxable - 8037           </option>" +
				"<option value=\"8039\">Prorated Instant Asmt Rs N Residential Taxable - 8039           </option>" +
				"<option value=\"8051\">Prorated Instant Asmt Cm N Commercial Taxable - 8051           </option>" +
				"<option value=\"8061\">Prorated Instant Asmt Cm N Commercial Taxable - 8061           </option>" +
				"<option value=\"8071\">Prorated Instant Asmt Cm N Commercial Taxable - 8071           </option>" +
				"<option value=\"8081\">Prorated instant Asmt Ind N Industrial Taxable - 8081           </option>" +
				"<option value=\"81\">Ind Land + Improve N Industrial Taxable - 81             </option>" +
				"<option value=\"85\">Industrial with Farm F Industrial Taxable - 85             </option>" +
				"<option value=\"89\">Pref Asd Ind(not1/3)10-30 N Industrial Taxable - 89             </option>" +
				"<option value=\"90\">Partial Exemption-vacant N Exempt Taxable - 90             </option>" +
				"<option value=\"9010\">Exempt Prop Rur Res - vac N Exempt Exempt - 9010           </option>" +
				"<option value=\"9011\">Exempt Prop Rur Res - imp N Exempt Exempt - 9011           </option>" +
				"<option value=\"9020\">Exempt Prop Farm - vac N Exempt Exempt - 9020           </option>" +
				"<option value=\"9021\">Exempt Prop Farm - imp N Exempt Exempt - 9021           </option>" +
				"<option value=\"9030\">Exempt Prop Res - vac N Exempt Exempt - 9030           </option>" +
				"<option value=\"9031\">Exempt Prop 1 Fam Res N Exempt Exempt - 9031           </option>" +
				"<option value=\"9032\">Exempt Prop 2 Fam Res N Exempt Exempt - 9032           </option>" +
				"<option value=\"9033\">Exempt Prop 3 Fam Res N Exempt Exempt - 9033           </option>" +
				"<option value=\"9034\">Exempt Prop 4 Fam Res N Exempt Exempt - 9034           </option>" +
				"<option value=\"9035\">Exempt Prop 5 Fam Res N Exempt Exempt - 9035           </option>" +
				"<option value=\"9036\">Exempt Prop 5 Fam Res N Exempt Exempt - 9036           </option>" +
				"<option value=\"9037\">Exempt Prop Condo Res N Exempt Exempt - 9037           </option>" +
				"<option value=\"9038\">Exempt Prop Imp Res No Dw N Exempt Exempt - 9038           </option>" +
				"<option value=\"9050\">Exempt Prop Vac Com N Exempt Exempt - 9050           </option>" +
				"<option value=\"9051\">Exempt Prop Com Res 6+ N Exempt Exempt - 9051           </option>" +
				"<option value=\"9061\">Exempt Prop Com Bus N Exempt Exempt - 9061           </option>" +
				"<option value=\"9071\">Exempt Prop Com Office N Exempt Exempt - 9071           </option>" +
				"<option value=\"9072\">Exempt Prop Govt Bldg N Exempt Exempt - 9072           </option>" +
				"<option value=\"9073\">Exempt Prop Educ Prop N Exempt Exempt - 9073           </option>" +
				"<option value=\"9074\">Exempt Prop Relig Prop N Exempt Exempt - 9074           </option>" +
				"<option value=\"9075\">Exempt Prop Soc/Charit N Exempt Exempt - 9075           </option>" +
				"<option value=\"9080\">Exempt Prop Vac Ind N Exempt Exempt - 9080           </option>" +
				"<option value=\"9081\">Exempt Prop Ind Land+Impr N Exempt - 9081           </option>" +
				"<option value=\"91\">Partially Exemp - Improve N Exempt Taxable - 91             </option>" +
			"</select>";
		TOWNSHIP_SELECT =
			"<select tabindex=\"200\" id=\"ddlTownship\" name=\"ddlTownship\">" +
				"<option value=\"\"> No Selection </option>" +
				"<option value=\"05\"> HARRISON</option>" +
				"<option value=\"08\"> PECATONICA</option>" +
				"<option value=\"14\"> SHIRLAND</option>" +
				"<option value=\"01\">BURRITT</option>" +
				"<option value=\"02\">CHERRY VALLEY</option>" +
				"<option value=\"03\">DURAND</option>" +
				"<option value=\"04\">HARLEM</option>" +
				"<option value=\"06\">LAONA</option>" +
				"<option value=\"07\">OWEN</option>" +
				"<option value=\"16\">ROCKFORD</option>" +
				"<option value=\"09\">ROCKTON</option>" +
				"<option value=\"11\">ROSCOE</option>" +
				"<option value=\"13\">SEWARD</option>" +
				"<option value=\"15\">WINNEBAGO</option>" +
			"</select>";

	}

}
