package ro.cst.tsearch.servers.types;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

import org.apache.log4j.Category;
import org.apache.log4j.Logger;

import ro.cst.tsearch.utils.RegExUtils;
import ro.cst.tsearch.utils.StringUtils;

/**
 * 
 * @author Oprina George
 * 
 *         Aug 12, 2011
 */

public class XXGenericPublicDataParentSiteConfiguration {
	public static List<String[][]> listOfOptions_state = new ArrayList<String[][]>();
	public static List<String[][]> listOfOptions_county = new ArrayList<String[][]>();
	public static List<String[][]> professionalLicenceListOfOptions = new ArrayList<String[][]>();
	public static List<String[][]> propertyTaxListOfOptions = new ArrayList<String[][]>();

	/**
	 * @param readTextFile
	 * @return
	 */
	public static String[][] readTextFileToMatrix(String firstRecord,
			String readTextFile) {
		String patru = "input type=\\\"?radio\\\"?.*?value=\\\"?(.*?)\\\".*?>.*?(?:<i>)?(?:.*?)(?:</i>)?(.*?)<a?";
		String pdQueryCase = "<a href=\"/pdquery.php.*?<i>(.*?)</i></a>";
		if (readTextFile.matches(pdQueryCase)) {
			readTextFile = readTextFile.replaceAll(pdQueryCase,
					"$1<a href=''> </a> ");
		}
		List<HashMap<String, String>> options = RegExUtils.getMatchesAsMap(
				patru, readTextFile, 1, 2);

		// StringBuilder l = new StringBuilder("{");
		String[][] a = new String[options.size() + 1][2];
		int i = 1;
		a[0] = new String[] { firstRecord, "Search All Items Below" };
		for (HashMap<String, String> option : options) {
			a[i++] = new String[] {
					StringUtils.cleanHtml(option.get("1")).trim(),
					StringUtils.cleanHtml(option.get("2")).trim() };

			// l = l.append( String.format(" { \"%s\" , \"%s\"  },",
			// option.get("1").trim(), option.get("2").trim()) );
		}

		// l= l.append("}");
		return a;
	}

	public static String[] SEARCH_ALL_ITEMS_BELOW = { "GRP_CIV_NAME",
			"GRP_MW_NAME", "GRP_SXO_NAME", "GRP_CRI_NAME", "GRP_PL_NAME",
			"GRP_TERROR_KB_NAME", "GRP_CAD_NAME", "GRP_VOTER_NAME",
			"GRP_DL_NAME", "GRP_SOS_NAME" };

	public static List<String> SEARCH_ALL_ITEMS_BELOW_LIST = Arrays
			.asList(SEARCH_ALL_ITEMS_BELOW);

	public static String[][] CIVIL_COURT_NAME_SEARCH_OPTIONS = {
			{ "GRP_CIV_NAME", "Search All Items Below" },
			{ "akaoc_name", "Alaska Criminal Courts" },
			{ "azaoc_party", "Arizona AOC" },
			{ "grp_civ_ca_name", "California Searches" },
			{ "grp_civ_CO_name", "Colorado Searches" },
			{ "grp_civ_CT_name", "Connecticut Civil Name Search" },
			{ "grp_civ_fl_name", "Florida Searches" },
			{ "grp_civ_GA_name", "Georgia Searches" },
			{ "grp_civ_hi_name", "Hawaii Searches" },
			{ "grp_civ_IL_name", "Illinois Searches" },
			{ "grp_civ_ia_name", "Iowa Searches" },
			{ "grp_civ_KY_name", "Kentucky Searches" },
			{ "grp_civ_la_name", "Louisiana Civil Searches" },
			{ "grp_civ_ME_name", "Maine Searches" },
			{ "grp_civ_MD_name", "Maryland Searches" },
			{ "grp_civ_NY_name", "New York Searches" },
			{ "grp_civ_nd_name", "North Dakota Civil" },
			{ "grp_civ_OK_name", "Oklahoma Searches" },
			{ "grp_civ_pa_name", "Pennsylvania Searches" },
			{ "grp_civ_TX_name", "Texas Civil Name Search" },
			{ "grp_civ_wv_name", "West Virginia Civil Name Search" },
			{ "grp_civ_WI_name", "Wisconsin Civil Name Search" } };

	// expand options for CIVIL COURT for each state
	public static String[][] CIVIL_COURT_NAME_SEARCH_TX = {
			{ "GRP_CIV_TX_NAME", "Search All Items Below" },
			{ "TX_MARRIAGE_NAME",
					"TX Marriage License Applications [1966-2003, 2005-08]" },
			{ "TX_MARRIAGE_NEW", "TX Marriage License Applications [2004]" },
			{ "TX_UNCLAIMED_PROP",
					"Texas Office of the Comptroller - Unclaimed Property" },
			{ "tx_divorce_name",
					"TX Report of Divorce Index [1968-2003, 2005-08]" },
			{ "tx_divorce_new", "TX Report of Divorce Index [2004]" },
			{ "TX_BRAZORIA_CIVIL_NM", "TX Brazoria District Court - Civil" },
			{ "TX_COLLIN_CIVIL_DEF", "TX Collin Civil Court [Defendants]" },
			{ "TX_COLLIN_CIVIL_PLTF", "TX Collin Civil Court [Plaintiffs]" },
			{ "dalcivp", "TX Dallas Civil Court [Prior to Nov. 2005]" },
			{ "txdal_civn", "TX Dallas Civil Courts [Nov. 2005 - Present]" },
			{ "TXDAL_STAT_NM",
					"TX Dallas Civil Courts Statistical Closure [Oct. 2008 - Present]" },
			{ "txdal_civ_famn", "TX Dallas Family Courts [Nov. 2005 - Present]" },
			{ "txcvdale", "TX Dallas Cnty Evictions" },
			{ "TX_HOOD_CIVIL_NM", "TX Hood Civil Court" },
			{ "TX_KERR_CIVIL", "TX Kerr Civil" } };

	public static String[][] MOST_WANTED_NAME_SEARCH_OPTIONS = {
			{ "GRP_MW_NAME", "Search All Items Below" },
			{ "GRP_DEA_MW", "DEA Most Wanted Name Search" },
			{ "GRP_FBI_MW_NAME", "FBI Name Search" },
			{ "GRP_ATF_MOSTWANTED", "ATF Most Wanted Name Search" },
			{ "GRP_SS_MOSTWANTED", "Secret Service Most Wanted Name Search" },
			{ "GRP_USAF_NAME", "Air Force Fugitive Name Search" },
			{ "GRP_USMAR_NAME", "US Marshals Most Wanted Search" },
			{ "GRP_USPS_MW_NAME", "US Postal Service Most Wanted Name Search" } };

	public static String[][] SEX_OFFENDER_NAME_SEARCH_OPTIONS = {
			{ "GRP_SXO_NAME", "Search All Items Below" },
			{ "grp_sxo_al_name", "Alabama" }, { "grp_sxo_ak_name", "Alaska" },
			{ "grp_sxo_az_name", "Arizona" },
			{ "grp_sxo_ar_name", "Arkansas" },
			{ "grp_sxo_ca_name", "California" },
			{ "grp_sxo_co_name", "Colorado" },
			{ "grp_sxo_ct_name", "Connecticut" },
			{ "grp_sxo_de_name", "Delaware" },
			{ "grp_sxo_dc_name", "District of Columbia" },
			{ "grp_sxo_fl_name", "Florida" }, { "grp_sxo_ga_name", "Georgia" },
			{ "grp_sxo_hi_name", "Hawaii" }, { "grp_sxo_id_name", "Idaho" },
			{ "grp_sxo_il_name", "Illinois" },
			{ "grp_sxo_in_name", "Indiana" }, { "grp_sxo_ia_name", "Iowa" },
			{ "grp_sxo_ks_name", "Kansas" }, { "grp_sxo_ky_name", "Kentucky" },
			{ "grp_sxo_la_name", "Louisiana" }, { "grp_sxo_me_name", "Maine" },
			{ "grp_sxo_md_name", "Maryland" },
			{ "grp_sxo_ma_name", "Massachusetts" },
			{ "grp_sxo_mi_name", "Michigan" },
			{ "grp_sxo_mn_name", "Minnesota" },
			{ "grp_sxo_ms_name", "Mississippi" },
			{ "grp_sxo_mo_name", "Missouri" },
			{ "grp_sxo_mt_name", "Montana" },
			{ "grp_sxo_ne_name", "Nebraska" }, { "grp_sxo_nv_name", "Nevada" },
			{ "grp_sxo_nh_name", "New Hampshire" },
			{ "grp_sxo_nj_name", "New Jersey" },
			{ "grp_sxo_nm_name", "New Mexico" },
			{ "grp_sxo_ny_name", "New York" },
			{ "grp_sxo_nc_name", "North Carolina" },
			{ "grp_sxo_nd_name", "North Dakota" },
			{ "grp_sxo_oh_name", "Ohio" }, { "grp_sxo_ok_name", "Oklahoma" },
			{ "grp_sxo_or_name", "Oregon" },
			{ "grp_sxo_pa_name", "Pennsylvania" },
			{ "grp_sxo_ri_name", "Rhode Island" },
			{ "grp_sxo_sc_name", "South Carolina" },
			{ "grp_sxo_sd_name", "South Dakota" },
			{ "grp_sxo_tn_name", "Tennessee" }, { "grp_sxo_tx_name", "Texas" },
			{ "grp_sxo_ut_name", "Utah" }, { "grp_sxo_vt_name", "Vermont" },
			{ "grp_sxo_va_name", "Virginia" },
			{ "grp_sxo_wa_name", "Washington" },
			{ "grp_sxo_wv_name", "West Virginia" },
			{ "grp_sxo_wi_name", "Wisconsin" },
			{ "grp_sxo_wy_name", "Wyoming" } };

	// expand options for SEX OFFENDER for each state
	public static String[][] SEX_OFFENDER_NAME_SEARCH_TX = {
			{ "GRP_SXO_TX_NAME", "Search All Items Below" },
			{ "TXSOR_NAME", "Texas Sex Offenders" },
			{ "TXSOR_ALIAS_NAME", "Texas Sex Offenders [Alias]" } };

	public static String[][] CRIMINAL_NAME_SEARCH_OPTIONS = {
			{ "GRP_CRI_NAME", "Search All Items Below" },
			{ "grp_cri_AL_name", "Alabama" }, { "grp_cri_AK_name", "Alaska" },
			{ "grp_cri_AZ_name", "Arizona" },
			{ "grp_cri_AR_name", "Arkansas" },
			{ "grp_cri_CA_name", "California" },
			{ "grp_cri_CO_name", "Colorado" },
			{ "grp_cri_CT_name", "Connecticut" },
			{ "grp_cri_de_name", "Delaware" },
			{ "grp_cri_FL_name", "Florida" }, { "grp_cri_GA_name", "Georgia" },
			{ "grp_cri_HI_name", "Hawaii" }, { "grp_cri_ID_name", "Idaho" },
			{ "grp_cri_IL_name", "Illinois" },
			{ "grp_cri_IN_name", "Indiana" }, { "grp_cri_IA_name", "Iowa" },
			{ "grp_cri_KS_name", "Kansas" }, { "grp_cri_KY_name", "Kentucky" },
			{ "grp_cri_LA_name", "Louisiana" },
			{ "grp_cri_MD_name", "Maryland" },
			{ "grp_cri_MA_name", "Massachusetts" },
			{ "grp_cri_MI_name", "Michigan" },
			{ "grp_cri_MN_name", "Minnesota" },
			{ "grp_cri_MS_name", "Mississippi" },
			{ "grp_cri_MO_name", "Missouri" },
			{ "grp_cri_MT_name", "Montana" },
			{ "grp_cri_NE_name", "Nebraska" }, { "grp_cri_NV_name", "Nevada" },
			{ "grp_cri_NH_name", "New Hampshire" },
			{ "grp_cri_NJ_name", "New Jersey" },
			{ "grp_cri_NM_name", "New Mexico" },
			{ "grp_cri_NY_name", "New York" },
			{ "grp_cri_NC_name", "North Carolina" },
			{ "grp_cri_ND_name", "North Dakota Criminal" },
			{ "grp_cri_OH_name", "Ohio" }, { "grp_cri_OK_name", "Oklahoma" },
			{ "grp_cri_OR_name", "Oregon" },
			{ "grp_cri_PA_name", "Pennsylvania" },
			{ "grp_cri_RI_name", "Rhode Island" },
			{ "grp_cri_SC_name", "South Carolina" },
			{ "grp_cri_TN_name", "Tennessee" }, { "grp_cri_TX_name", "Texas" },
			{ "grp_cri_UT_name", "Utah" }, { "grp_cri_VT_name", "Vermont" },
			{ "grp_cri_VA_name", "Virginia" },
			{ "grp_cri_WA_name", "Washington" },
			{ "grp_cri_WV_name", "West Virginia" },
			{ "grp_cri_WI_name", "Wisconsin" } };

	public static String[][] CRIMINAL_NAME_SEARCH_TX = {
			{ "GRP_CRI_TX_NAME", "Search All Items Below" },
			{ "txdcjpa", "TX DCJ Parole/Probation" },
			{ "txdcj_rec", "Texas Dept. of Criminal Justice" },
			{ "txdps_name", "Texas Department of Public Safety" },
			{ "tx_amarillo_warrant",
					"TX Amarillo Municipal Court Active Warrants" },
			{ "TX_ARLINGTON_NEW_WAR",
					"TX Arlington Outstanding Arrest Warrants" },
			{ "TX_BEXAR_CRIM", "TX Bexar Criminal" },
			{ "TX_BRAZORIA_CRIM", "TX Brazoria District Court - Criminal" },
			{ "TX_BRAZOS_CRIM", "TX Brazos Criminal" },
			{ "TX_BURNET_CRIM", "TX Burnet Criminal" },
			{ "TX_CARROLLTON_WARRAN", "TX Carrollton Arrest Warrants" },
			{ "TX_COLLIN_CRIM_DEF", "TX Collin Criminal" },
			{ "tx_collin_warrant", "Collin, Texas Active Warrants" },
			{ "tx_collin_wanted", "Collin, Texas Most Wanted" },
			{ "TX_COMAL_CRIM", "TX Comal Criminal" },
			{ "tx_dallas_warrant", "TX Dallas (City of) Current Warrants" },
			{ "tx_dallas_co_warrant", "TX Dallas (County of) Current Warrants" },
			{ "dalcrimm", "TX Dallas County Criminal" },
			{ "TX_DENTON_CRIM", "TX Denton Criminal [Filed 1990-2005]" },
			{ "TX_DENTON_CRIM_DISP",
					"TX Denton Criminal [Disposed 2006-Present]" },
			{ "TX_ECTOR_WARRANTS", "TX Ector Outstanding Warrants" },
			{ "tx_el_paso_warrant", "El Paso, Texas Outstanding Warrants" },
			{ "TX_FORT_BEND_CRIM", "TX Fort Bend Criminal [1980-Present]" },
			{ "TX_GALVESTON_WARRANT", "TX Galveston Outstanding Warrants" },
			{ "tx_garland_warrant", "TX Garland Open Warrants" },
			{ "tx_grayson_warrant", "TX Grayson Warrants" },
			{ "TX_GREGG_CRIM", "TX Gregg Criminal" },
			{ "TX_HARRIS_FEL", "TX Harris Criminal [Fel.]" },
			{ "TX_HARRIS_FEL_AN", "TX Harris Criminal [Fel. Alias]" },
			{ "TX_HARRIS_MISD", "TX Harris Criminal [Misd.]" },
			{ "TX_HARRIS_MISD_AN", "TX Harris Criminal [Misd. Alias]" },
			{ "tx_hemphill_warrant", "Hemphill, TX Active Warrants" },
			{ "TX_HENDERSON_CRIM", "TX Henderson Criminal" },
			{ "TX_HOOD_CRIMINAL", "TX Hood Criminal [July 1997 - Present]" },
			{ "TX_JEFFERSON_CRIM_D", "TX Jefferson Criminal" },
			{ "tx_jefferson_war_new", "TX Jefferson Outstanding Warrants" },
			{ "tx_kaufman_warrant",
					"TX Kaufman Active Capias Pro Fine Warrants" },
			{ "TX_KERR_CRIM", "TX Kerr Criminal" },
			{ "tx_lamar_crim", "TX Lamar Criminal" },
			{ "TX_MCLENNAN_WARRANTS", "TX McLennan Outstanding Warrants" },
			{ "tx_midland_war_const", "TX Midland Constable Warrants" },
			{ "tx_midland_hotcheck", "TX Midland Hot Check Warrants" },
			{ "TX_MONTGOMERY_CRIM", "TX Montgomery Criminal" },
			{ "tx_orange_f_warrant", "TX Orange County Felony Warrants" },
			{ "tx_orange_j_warrant",
					"TX Orange County Justice of the Peace Warrants" },
			{ "tx_orange_m_warrant",
					"TX Orange County Courts at Law (Misdemeanor) Warrants" },
			{ "tx_plano_warrant", "TX Plano Arrest Warrants" },
			{ "tx_potter_crim", "TX Potter Criminal" },
			{ "tx_potter_alias", "TX Potter Criminal [Alias]" },
			{ "tx_potter_warrant", "TX Potter County Active Warrants" },
			{ "TX_RANDALL_WARRANTS", "TX Randall Outstanding Warrants" },
			{ "TX_SMITH_CRIM", "TX Smith Criminal" },
			{ "tx_waco_warrant", "TX Waco Arrest Warrants" },
			{ "TX_WILLIAMSON_CRIM", "TX Williamson Criminal" }, };

	public static String[][] TERRORISM_NAME_SEARCH_OPTIONS = {
			{ "GRP_TERROR_KB_NAME", "Search All Items Below" },
			{ "TERROR_KB", "Terrorism Knowledge Base" },
			{ "TERROR_KB_AN", "Terrorism Knowledge Base [Alias]" }, };
	public static String[][] VOTER_NAME_SEARCH_OPTIONS = {
			{ "GRP_VOTER_NAME", "Search All Items Below" },
			{ "grp_voter_AR_name", "Arkansas Voter" },
			{ "DC_VOTER", "District of Columbia Voter" },
			{ "grp_voter_FL_name", "Florida Voter" },
			{ "grp_voter_ID_name", "Idaho Voter" },
			{ "grp_voter_MA_name", "Massachusetts Voter" },
			{ "grp_voter_MI_name", "Michigan Voter" },
			{ "grp_voter_NH_name", "New Hampshire Voter" },
			{ "grp_voter_NY_name", "New York Voter" },
			{ "grp_voter_NC_name", "North Carolina Voter" },
			{ "grp_voter_OH_name", "Ohio Voter" },
			{ "grp_voter_OK_name", "Oklahoma Voter" },
			{ "grp_voter_RI_name", "Rhode Island Voter" },
			{ "grp_voter_TX_name", "Texas Voter" } };

	public static String[][] VOTER_NAME_SEARCH_TX = {
			{ "GRP_VOTER_TX_NAME", "Search All Items Below" },
			{ "GRP_VOTER_TX_FULLNAME", "Search All Items Voter" },
			{ "GRP_VOTER_TX_MA_NAME", "Search All Items Voter [Maiden Name]" },
			{ "TX_ANDERSON_VOT", "TX Anderson Voter" },
			{ "TX_ANDREWS_VOT", "TX Andrews Voter" },
			{ "TX_ANGELINA_VOT", "TX Angelina Voter" },
			{ "TX_ARANSAS_VOT", "TX Aransas Voter" },
			{ "TX_ARCHER_VOT", "TX Archer Voter" },
			{ "TX_ARMSTRONG_VOT", "TX Armstrong Voter" },
			{ "TX_ATASCOSA_VOT", "TX Atascosa Voter" },
			{ "TX_AUSTIN_VOT", "TX Austin Voter" },
			{ "TX_BAILEY_VOT", "TX Bailey Voter" },
			{ "TX_BANDERA_VOT", "TX Bandera Voter" },
			{ "TX_BASTROP_VOT", "TX Bastrop Voter" },
			{ "TX_BAYLOR_VOT", "TX Baylor Voter" },
			{ "TX_BEE_VOT", "TX Bee Voter" },
			{ "TX_BELL_VOT", "TX Bell Voter" },
			{ "TX_BEXAR_VOT", "TX Bexar Voter" },
			{ "TX_BLANCO_VOT", "TX Blanco Voter" },
			{ "TX_BORDEN_VOT", "TX Borden Voter" },
			{ "TX_BOSQUE_VOT", "TX Bosque Voter" },
			{ "TX_BOWIE_VOT", "TX Bowie Voter" },
			{ "TX_BRAZORIA_VOT", "TX Brazoria Voter" },
			{ "TX_BRAZOS_VOT", "TX Brazos Voter" },
			{ "TX_BREWSTER_VOT", "TX Brewster Voter" },
			{ "TX_BRISCOE_VOT", "TX Briscoe Voter" },
			{ "TX_BROOKS_VOT", "TX Brooks Voter" },
			{ "TX_BROWN_VOT", "TX Brown Voter" },
			{ "TX_BURLESON_VOT", "TX Burleson Voter" },
			{ "TX_BURNET_VOT", "TX Burnet Voter" },
			{ "TX_CALDWELL_VOT", "TX Caldwell Voter" },
			{ "TX_CALHOUN_VOT", "TX Calhoun Voter" },
			{ "TX_CALLAHAN_VOT", "TX Callahan Voter" },
			{ "TX_CAMERON_VOT", "TX Cameron Voter" },
			{ "TX_CAMP_VOT", "TX Camp Voter" },
			{ "TX_CARSON_VOT", "TX Carson Voter" },
			{ "TX_CASS_VOT", "TX Cass Voter" },
			{ "TX_CASTRO_VOT", "TX Castro Voter" },
			{ "TX_CHAMBERS_VOT", "TX Chambers Voter" },
			{ "TX_CHEROKEE_VOT", "TX Cherokee Voter" },
			{ "TX_CHILDRESS_VOT", "TX Childress Voter" },
			{ "TX_CLAY_VOT", "TX Clay Voter" },
			{ "TX_COCHRAN_VOT", "TX Cochran Voter" },
			{ "TX_COKE_VOT", "TX Coke Voter" },
			{ "TX_COLEMAN_VOT", "TX Coleman Voter" },
			{ "TX_COLLIN_VOT", "TX Collin Voter" },
			{ "TX_COLLINGSWORTH_VOT", "TX Collingsworth Voter" },
			{ "TX_COLORADO_VOT", "TX Colorado Voter" },
			{ "TX_COMAL_VOT", "TX Comal Voter" },
			{ "TX_COMANCHE_VOT", "TX Comanche Voter" },
			{ "TX_CONCHO_VOT", "TX Concho Voter" },
			{ "TX_COOKE_VOT", "TX Cooke Voter" },
			{ "TX_CORYELL_VOT", "TX Coryell Voter" },
			{ "TX_COTTLE_VOT", "TX Cottle Voter" },
			{ "TX_CRANE_VOT", "TX Crane Voter" },
			{ "TX_CROCKETT_VOT", "TX Crockett Voter" },
			{ "TX_CROSBY_VOT", "TX Crosby Voter" },
			{ "TX_CULBERSON_VOT", "TX Culberson Voter" },
			{ "TX_DALLAM_VOT", "TX Dallam Voter" },
			{ "TX_DALLAS_VOT", "TX Dallas Voter" },
			{ "TX_DAWSON_VOT", "TX Dawson Voter" },
			{ "TX_DEAFSMITH_VOT", "TX Deaf Smith Voter" },
			{ "TX_DELTA_VOT", "TX Delta Voter" },
			{ "TX_DENTON_VOT", "TX Denton Voter" },
			{ "TX_DEWITT_VOT", "TX DeWitt Voter" },
			{ "TX_DICKENS_VOT", "TX Dickens Voter" },
			{ "TX_DIMMIT_VOT", "TX Dimmit Voter" },
			{ "TX_DONLEY_VOT", "TX Donley Voter" },
			{ "TX_DUVAL_VOT", "TX Duval Voter" },
			{ "TX_EASTLAND_VOT", "TX Eastland Voter" },
			{ "TX_ECTOR_VOT", "TX Ector Voter" },
			{ "TX_EDWARDS_VOT", "TX Edwards Voter" },
			{ "TX_EL_PASO_VOT", "TX El Paso Voter" },
			{ "TX_ELLIS_VOT", "TX Ellis Voter" },
			{ "TX_ERATH_VOT", "TX Erath Voter" },
			{ "TX_FALLS_VOT", "TX Falls Voter" },
			{ "TX_FANNIN_VOT", "TX Fannin Voter" },
			{ "TX_FAYETTE_VOT", "TX Fayette Voter" },
			{ "TX_FISHER_VOT", "TX Fisher Voter" },
			{ "TX_FLOYD_VOT", "TX Floyd Voter" },
			{ "TX_FOARD_VOT", "TX Foard Voter" },
			{ "TX_FORTBEND_VOT", "TX Fort Bend Voter" },
			{ "TX_FRANKLIN_VOT", "TX Franklin Voter" },
			{ "TX_FREESTONE_VOT", "TX Freestone Voter" },
			{ "TX_FRIO_VOT", "TX Frio Voter" },
			{ "TX_GAINES_VOT", "TX Gaines Voter" },
			{ "TX_GALVESTON_VOT", "TX Galveston Voter" },
			{ "TX_GARZA_VOT", "TX Garza Voter" },
			{ "TX_GILLESPIE_VOT", "TX Gillespie Voter" },
			{ "TX_GLASSCOCK_VOT", "TX Glasscock Voter" },
			{ "TX_GOLIAD_VOT", "TX Goliad Voter" },
			{ "TX_GONZALES_VOT", "TX Gonzales Voter" },
			{ "TX_GRAY_VOT", "TX Gray Voter" },
			{ "TX_GRAYSON_VOT", "TX Grayson Voter" },
			{ "TX_GREGG_VOT", "TX Gregg Voter" },
			{ "TX_GRIMES_VOT", "TX Grimes Voter" },
			{ "TX_GUADALUPE_VOT", "TX Guadalupe Voter" },
			{ "TX_HALE_VOT", "TX Hale Voter" },
			{ "TX_HALL_VOT", "TX Hall Voter" },
			{ "TX_HAMILTON_VOT", "TX Hamilton Voter" },
			{ "TX_HANSFORD_VOT", "TX Hansford Voter" },
			{ "TX_HARDEMAN_VOT", "TX Hardeman Voter" },
			{ "TX_HARDIN_VOT", "TX Hardin Voter" },
			{ "TX_HARRIS_VOT", "TX Harris Voter" },
			{ "TX_HARRISON_VOT", "TX Harrison Voter" },
			{ "TX_HARTLEY_VOT", "TX Hartley Voter" },
			{ "TX_HASKELL_VOT", "TX Haskell Voter" },
			{ "TX_HAYS_VOT", "TX Hays Voter" },
			{ "TX_HEMPHILL_VOT", "TX Hemphill Voter" },
			{ "TX_HENDERSON_VOT", "TX Henderson Voter" },
			{ "TX_HIDALGO_VOT", "TX Hidalgo Voter" },
			{ "TX_HILL_VOT", "TX Hill Voter" },
			{ "TX_HOCKLEY_VOT", "TX Hockley Voter" },
			{ "TX_HOOD_VOT", "TX Hood Voter" },
			{ "TX_HOPKINS_VOT", "TX Hopkins Voter" },
			{ "TX_HOUSTON_VOT", "TX Houston Voter" },
			{ "TX_HOWARD_VOT", "TX Howard Voter" },
			{ "TX_HUDSPETH_VOT", "TX Hudspeth Voter" },
			{ "TX_HUNT_VOT", "TX Hunt Voter" },
			{ "TX_HUTCHINSON_VOT", "TX Hutchinson Voter" },
			{ "TX_IRION_VOT", "TX Irion Voter" },
			{ "TX_JACK_VOT", "TX Jack Voter" },
			{ "TX_JACKSON_VOT", "TX Jackson Voter" },
			{ "TX_JASPER_VOT", "TX Jasper Voter" },
			{ "TX_JEFFDAVIS_VOT", "TX Jeff Davis Voter" },
			{ "TX_JEFFERSON_VOT", "TX Jefferson Voter" },
			{ "TX_JIMHOGG_VOT", "TX Jim Hogg Voter" },
			{ "TX_JIMWELLS_VOT", "TX Jim Wells Voter" },
			{ "TX_JOHNSON_VOT", "TX Johnson Voter" },
			{ "TX_JONES_VOT", "TX Jones Voter" },
			{ "TX_KARNES_VOT", "TX Karnes Voter" },
			{ "TX_KAUFMAN_VOT", "TX Kaufman Voter" },
			{ "TX_KENDALL_VOT", "TX Kendall Voter" },
			{ "TX_KENEDY_VOT", "TX Kenedy Voter" },
			{ "TX_KENT_VOT", "TX Kent Voter" },
			{ "TX_KERR_VOT", "TX Kerr Voter" },
			{ "TX_KIMBLE_VOT", "TX Kimble Voter" },
			{ "TX_KING_VOT", "TX King Voter" },
			{ "TX_KINNEY_VOT", "TX Kinney Voter" },
			{ "TX_KLEBERG_VOT", "TX Kleberg Voter" },
			{ "TX_KNOX_VOT", "TX Knox Voter" },
			{ "TX_LA_SALLE_VOT", "TX La Salle Voter" },
			{ "TX_LAMAR_VOT", "TX Lamar Voter" },
			{ "TX_LAMB_VOT", "TX Lamb Voter" },
			{ "TX_LAMPASAS_VOT", "TX Lampasas Voter" },
			{ "TX_LAVACA_VOT", "TX Lavaca Voter" },
			{ "TX_LEE_VOT", "TX Lee Voter" },
			{ "TX_LEON_VOT", "TX Leon Voter" },
			{ "TX_LIBERTY_VOT", "TX Liberty Voter" },
			{ "TX_LIMESTONE_VOT", "TX Limestone Voter" },
			{ "TX_LIPSCOMB_VOT", "TX Lipscomb Voter" },
			{ "TX_LIVEOAK_VOT", "TX Live Oak Voter" },
			{ "TX_LLANO_VOT", "TX Llano Voter" },
			{ "TX_LOVING_VOT", "TX Loving Voter" },
			{ "TX_LUBBOCK_VOT", "TX Lubbock Voter" },
			{ "TX_LYNN_VOT", "TX Lynn Voter" },
			{ "TX_MADISON_VOT", "TX Madison Voter" },
			{ "TX_MARION_VOT", "TX Marion Voter" },
			{ "TX_MARTIN_VOT", "TX Martin Voter" },
			{ "TX_MASON_VOT", "TX Mason Voter" },
			{ "TX_MATAGORDA_VOT", "TX Matagorda Voter" },
			{ "TX_MAVERICK_VOT", "TX Maverick Voter" },
			{ "TX_MCCULLOCH_VOT", "TX McCulloch Voter" },
			{ "TX_MCLENNAN_VOT", "TX McLennan Voter" },
			{ "TX_MCMULLEN_VOT", "TX McMullen Voter" },
			{ "TX_MEDINA_VOT", "TX Medina Voter" },
			{ "TX_MENARD_VOT", "TX Menard Voter" },
			{ "TX_MIDLAND_VOT", "TX Midland Voter" },
			{ "TX_MILAM_VOT", "TX Milam Voter" },
			{ "TX_MILLS_VOT", "TX Mills Voter" },
			{ "TX_MITCHELL_VOT", "TX Mitchell Voter" },
			{ "TX_MONTAGUE_VOT", "TX Montague Voter" },
			{ "TX_MONTGOMERY_VOT", "TX Montgomery Voter" },
			{ "TX_MOORE_VOT", "TX Moore Voter" },
			{ "TX_MORRIS_VOT", "TX Morris Voter" },
			{ "TX_MOTLEY_VOT", "TX Motley Voter" },
			{ "TX_NACOGDOCHES_VOT", "TX Nacogdoches Voter" },
			{ "TX_NAVARRO_VOT", "TX Navarro Voter" },
			{ "TX_NEWTON_VOT", "TX Newton Voter" },
			{ "TX_NOLAN_VOT", "TX Nolan Voter" },
			{ "TX_NUECES_VOT", "TX Nueces Voter" },
			{ "TX_OCHILTREE_VOT", "TX Ochiltree Voter" },
			{ "TX_OLDHAM_VOT", "TX Oldham Voter" },
			{ "TX_ORANGE_VOT", "TX Orange Voter" },
			{ "TX_PALOPINTO_VOT", "TX Palo Pinto Voter" },
			{ "TX_PANOLA_VOT", "TX Panola Voter" },
			{ "TX_PARKER_VOT", "TX Parker Voter" },
			{ "TX_PARMER_VOT", "TX Parmer Voter" },
			{ "TX_PECOS_VOT", "TX Pecos Voter" },
			{ "TX_POLK_VOT", "TX Polk Voter" },
			{ "TX_POTTER_VOT", "TX Potter Voter" },
			{ "TX_PRESIDIO_VOT", "TX Presidio Voter" },
			{ "TX_RAINS_VOT", "TX Rains Voter" },
			{ "TX_RANDALL_VOT", "TX Randall Voter" },
			{ "TX_REAGAN_VOT", "TX Reagan Voter" },
			{ "TX_REAL_VOT", "TX Real Voter" },
			{ "TX_REDRIVER_VOT", "TX Red River Voter" },
			{ "TX_REEVES_VOT", "TX Reeves Voter" },
			{ "TX_REFUGIO_VOT", "TX Refugio Voter" },
			{ "TX_ROBERTS_VOT", "TX Roberts Voter" },
			{ "TX_ROBERTSON_VOT", "TX Robertson Voter" },
			{ "TX_ROCKWALL_VOT", "TX Rockwall Voter" },
			{ "TX_RUNNELS_VOT", "TX Runnels Voter" },
			{ "TX_RUSK_VOT", "TX Rusk Voter" },
			{ "TX_SABINE_VOT", "TX Sabine Voter" },
			{ "TX_SANAUGUSTINE_VOT", "TX San Augustine Voter" },
			{ "TX_SANJACINTO_VOT", "TX San Jacinto Voter" },
			{ "TX_SANPATRICIO_VOT", "TX San Patricio Voter" },
			{ "TX_SANSABA_VOT", "TX San Saba Voter" },
			{ "TX_SCHLEICHER_VOT", "TX Schleicher Voter" },
			{ "TX_SCURRY_VOT", "TX Scurry Voter" },
			{ "TX_SHACKELFORD_VOT", "TX Shackelford Voter" },
			{ "TX_SHELBY_VOT", "TX Shelby Voter" },
			{ "TX_SHERMAN_VOT", "TX Sherman Voter" },
			{ "TX_SMITH_VOT", "TX Smith Voter" },
			{ "TX_SOMERVELL_VOT", "TX Somervell Voter" },
			{ "TX_STARR_VOT", "TX Starr Voter" },
			{ "TX_STEPHENS_VOT", "TX Stephens Voter" },
			{ "TX_STERLING_VOT", "TX Sterling Voter" },
			{ "TX_STONEWALL_VOT", "TX Stonewall Voter" },
			{ "TX_SUTTON_VOT", "TX Sutton Voter" },
			{ "TX_SWISHER_VOT", "TX Swisher Voter" },
			{ "TX_TARRANT_VOT", "TX Tarrant Voter" },
			{ "TX_TAYLOR_VOT", "TX Taylor Voter" },
			{ "TX_TERRELL_VOT", "TX Terrell Voter" },
			{ "TX_TERRY_VOT", "TX Terry Voter" },
			{ "TX_THROCKMORTON_VOT", "TX Throckmorton Voter" },
			{ "TX_TITUS_VOT", "TX Titus Voter" },
			{ "TX_TOMGREEN_VOT", "TX Tom Green Voter" },
			{ "TX_TRAVIS_VOT", "TX Travis Voter" },
			{ "TX_TRINITY_VOT", "TX Trinity Voter" },
			{ "TX_TYLER_VOT", "TX Tyler Voter" },
			{ "TX_UPSHUR_VOT", "TX Upshur Voter" },
			{ "TX_UPTON_VOT", "TX Upton Voter" },
			{ "TX_UVALDE_VOT", "TX Uvalde Voter" },
			{ "TX_VALVERDE_VOT", "TX Val Verde Voter" },
			{ "TX_VANZANDT_VOT", "TX Van Zandt Voter" },
			{ "TX_VICTORIA_VOT", "TX Victoria Voter" },
			{ "TX_WALKER_VOT", "TX Walker Voter" },
			{ "TX_WALLER_VOT", "TX Waller Voter" },
			{ "TX_WARD_VOT", "TX Ward Voter" },
			{ "TX_WASHINGTON_VOT", "TX Washington Voter" },
			{ "TX_WEBB_VOT", "TX Webb Voter" },
			{ "TX_WHARTON_VOT", "TX Wharton Voter" },
			{ "TX_WHEELER_VOT", "TX Wheeler Voter" },
			{ "TX_WICHITA_VOT", "TX Wichita Voter" },
			{ "TX_WILBARGER_VOT", "TX Wilbarger Voter" },
			{ "TX_WILLACY_VOT", "TX Willacy Voter" },
			{ "TX_WILLIAMSON_VOT", "TX Williamson Voter" },
			{ "TX_WILSON_VOT", "TX Wilson Voter" },
			{ "TX_WINKLER_VOT", "TX Winkler Voter" },
			{ "TX_WISE_VOT", "TX Wise Voter" },
			{ "TX_WOOD_VOT", "TX Wood Voter" },
			{ "TX_YOAKUM_VOT", "TX Yoakum Voter" },
			{ "TX_YOUNG_VOT", "TX Young Voter" },
			{ "TX_ZAPATA_VOT", "TX Zapata Voter" },
			{ "TX_ZAVALA_VOT", "TX Zavala Voter" },
			{ "TX_ANDERSON_MA", "TX Anderson Voter [Maiden]" },
			{ "TX_ANDREWS_MA", "TX Andrews Voter [Maiden]" },
			{ "TX_ANGELINA_MA", "TX Angelina Voter [Maiden]" },
			{ "TX_ARANSAS_MA", "TX Aransas Voter [Maiden]" },
			{ "TX_ARCHER_MA", "TX Archer Voter [Maiden]" },
			{ "TX_ARMSTRONG_MA", "TX Armstrong Voter [Maiden]" },
			{ "TX_ATASCOSA_MA", "TX Atascosa Voter [Maiden]" },
			{ "TX_AUSTIN_MA", "TX Austin Voter [Maiden]" },
			{ "TX_BAILEY_MA", "TX Bailey Voter [Maiden]" },
			{ "TX_BANDERA_MA", "TX Bandera Voter [Maiden]" },
			{ "TX_BASTROP_MA", "TX Bastrop Voter [Maiden]" },
			{ "TX_BAYLOR_MA", "TX Baylor Voter [Maiden]" },
			{ "TX_BEE_MA", "TX Bee Voter [Maiden]" },
			{ "TX_BELL_MA", "TX Bell Voter [Maiden]" },
			{ "TX_BEXAR_MA", "TX Bexar Voter [Maiden]" },
			{ "TX_BLANCO_MA", "TX Blanco Voter [Maiden]" },
			{ "TX_BORDEN_MA", "TX Borden Voter [Maiden]" },
			{ "TX_BOSQUE_MA", "TX Bosque Voter [Maiden]" },
			{ "TX_BOWIE_MA", "TX Bowie Voter [Maiden]" },
			{ "TX_BRAZORIA_MA", "TX Brazoria Voter [Maiden]" },
			{ "TX_BRAZOS_MA", "TX Brazos Voter [Maiden]" },
			{ "TX_BREWSTER_MA", "TX Brewster Voter [Maiden]" },
			{ "TX_BRISCOE_MA", "TX Briscoe Voter [Maiden]" },
			{ "TX_BROOKS_MA", "TX Brooks Voter [Maiden]" },
			{ "TX_BROWN_MA", "TX Brown Voter [Maiden]" },
			{ "TX_BURLESON_MA", "TX Burleson Voter [Maiden]" },
			{ "TX_BURNET_MA", "TX Burnet Voter [Maiden]" },
			{ "TX_CALDWELL_MA", "TX Caldwell Voter [Maiden]" },
			{ "TX_CALHOUN_MA", "TX Calhoun Voter [Maiden]" },
			{ "TX_CALLAHAN_MA", "TX Callahan Voter [Maiden]" },
			{ "TX_CAMERON_MA", "TX Cameron Voter [Maiden]" },
			{ "TX_CAMP_MA", "TX Camp Voter [Maiden]" },
			{ "TX_CARSON_MA", "TX Carson Voter [Maiden]" },
			{ "TX_CASS_MA", "TX Cass Voter [Maiden]" },
			{ "TX_CASTRO_MA", "TX Castro Voter [Maiden]" },
			{ "TX_CHAMBERS_MA", "TX Chambers Voter [Maiden]" },
			{ "TX_CHEROKEE_MA", "TX Cherokee Voter [Maiden]" },
			{ "TX_CHILDRESS_MA", "TX Childress Voter [Maiden]" },
			{ "TX_CLAY_MA", "TX Clay Voter [Maiden]" },
			{ "TX_COCHRAN_MA", "TX Cochran Voter [Maiden]" },
			{ "TX_COKE_MA", "TX Coke Voter [Maiden]" },
			{ "TX_COLEMAN_MA", "TX Coleman Voter [Maiden]" },
			{ "TX_COLLIN_MA", "TX Collin Voter [Maiden]" },
			{ "TX_COLLINGSWORTH_MA", "TX Collingsworth Voter [Maiden]" },
			{ "TX_COLORADO_MA", "TX Colorado Voter [Maiden]" },
			{ "TX_COMAL_MA", "TX Comal Voter [Maiden]" },
			{ "TX_COMANCHE_MA", "TX Comanche Voter [Maiden]" },
			{ "TX_CONCHO_MA", "TX Concho Voter [Maiden]" },
			{ "TX_COOKE_MA", "TX Cooke Voter [Maiden]" },
			{ "TX_CORYELL_MA", "TX Coryell Voter [Maiden]" },
			{ "TX_COTTLE_MA", "TX Cottle Voter [Maiden]" },
			{ "TX_CRANE_MA", "TX Crane Voter [Maiden]" },
			{ "TX_CROCKETT_MA", "TX Crockett Voter [Maiden]" },
			{ "TX_CROSBY_MA", "TX Crosby Voter [Maiden]" },
			{ "TX_CULBERSON_MA", "TX Culberson Voter [Maiden]" },
			{ "TX_DALLAM_MA", "TX Dallam Voter [Maiden]" },
			{ "TX_DALLAS_MA", "TX Dallas Voter [Maiden]" },
			{ "TX_DAWSON_MA", "TX Dawson Voter [Maiden]" },
			{ "TX_DEAFSMITH_MA", "TX Deaf Smith Voter [Maiden]" },
			{ "TX_DELTA_MA", "TX Delta Voter [Maiden]" },
			{ "TX_DENTON_MA", "TX Denton Voter [Maiden]" },
			{ "TX_DEWITT_MA", "TX DeWitt Voter [Maiden]" },
			{ "TX_DICKENS_MA", "TX Dickens Voter [Maiden]" },
			{ "TX_DIMMIT_MA", "TX Dimmit Voter [Maiden]" },
			{ "TX_DONLEY_MA", "TX Donley Voter [Maiden]" },
			{ "TX_DUVAL_MA", "TX Duval Voter [Maiden]" },
			{ "TX_EASTLAND_MA", "TX Eastland Voter [Maiden]" },
			{ "TX_ECTOR_MA", "TX Ector Voter [Maiden]" },
			{ "TX_EDWARDS_MA", "TX Edwards Voter [Maiden]" },
			{ "TX_EL_PASO_MA", "TX El Paso Voter [Maiden]" },
			{ "TX_ELLIS_MA", "TX Ellis Voter [Maiden]" },
			{ "TX_ERATH_MA", "TX Erath Voter [Maiden]" },
			{ "TX_FALLS_MA", "TX Falls Voter [Maiden]" },
			{ "TX_FANNIN_MA", "TX Fannin Voter [Maiden]" },
			{ "TX_FAYETTE_MA", "TX Fayette Voter [Maiden]" },
			{ "TX_FISHER_MA", "TX Fisher Voter [Maiden]" },
			{ "TX_FLOYD_MA", "TX Floyd Voter [Maiden]" },
			{ "TX_FOARD_MA", "TX Foard Voter [Maiden]" },
			{ "TX_FORTBEND_MA", "TX Fort Bend Voter [Maiden]" },
			{ "TX_FRANKLIN_MA", "TX Franklin Voter [Maiden]" },
			{ "TX_FREESTONE_MA", "TX Freestone Voter [Maiden]" },
			{ "TX_FRIO_MA", "TX Frio Voter [Maiden]" },
			{ "TX_GAINES_MA", "TX Gaines Voter [Maiden]" },
			{ "TX_GALVESTON_MA", "TX Galveston Voter [Maiden]" },
			{ "TX_GARZA_MA", "TX Garza Voter [Maiden]" },
			{ "TX_GILLESPIE_MA", "TX Gillespie Voter [Maiden]" },
			{ "TX_GLASSCOCK_MA", "TX Glasscock Voter [Maiden]" },
			{ "TX_GOLIAD_MA", "TX Goliad Voter [Maiden]" },
			{ "TX_GONZALES_MA", "TX Gonzales Voter [Maiden]" },
			{ "TX_GRAY_MA", "TX Gray Voter [Maiden]" },
			{ "TX_GRAYSON_MA", "TX Grayson Voter [Maiden]" },
			{ "TX_GREGG_MA", "TX Gregg Voter [Maiden]" },
			{ "TX_GRIMES_MA", "TX Grimes Voter [Maiden]" },
			{ "TX_GUADALUPE_MA", "TX Guadalupe Voter [Maiden]" },
			{ "TX_HALE_MA", "TX Hale Voter [Maiden]" },
			{ "TX_HALL_MA", "TX Hall Voter [Maiden]" },
			{ "TX_HAMILTON_MA", "TX Hamilton Voter [Maiden]" },
			{ "TX_HANSFORD_MA", "TX Hansford Voter [Maiden]" },
			{ "TX_HARDEMAN_MA", "TX Hardeman Voter [Maiden]" },
			{ "TX_HARDIN_MA", "TX Hardin Voter [Maiden]" },
			{ "TX_HARRIS_MA", "TX Harris Voter [Maiden]" },
			{ "TX_HARRISON_MA", "TX Harrison Voter [Maiden]" },
			{ "TX_HARTLEY_MA", "TX Hartley Voter [Maiden]" },
			{ "TX_HASKELL_MA", "TX Haskell Voter [Maiden]" },
			{ "TX_HAYS_MA", "TX Hays Voter [Maiden]" },
			{ "TX_HEMPHILL_MA", "TX Hemphill Voter [Maiden]" },
			{ "TX_HENDERSON_MA", "TX Henderson Voter [Maiden]" },
			{ "TX_HIDALGO_MA", "TX Hidalgo Voter [Maiden]" },
			{ "TX_HILL_MA", "TX Hill Voter [Maiden]" },
			{ "TX_HOCKLEY_MA", "TX Hockley Voter [Maiden]" },
			{ "TX_HOOD_MA", "TX Hood Voter [Maiden]" },
			{ "TX_HOPKINS_MA", "TX Hopkins Voter [Maiden]" },
			{ "TX_HOUSTON_MA", "TX Houston Voter [Maiden]" },
			{ "TX_HOWARD_MA", "TX Howard Voter [Maiden]" },
			{ "TX_HUDSPETH_MA", "TX Hudspeth Voter [Maiden]" },
			{ "TX_HUNT_MA", "TX Hunt Voter [Maiden]" },
			{ "TX_HUTCHINSON_MA", "TX Hutchinson Voter [Maiden]" },
			{ "TX_IRION_MA", "TX Irion Voter [Maiden]" },
			{ "TX_JACK_MA", "TX Jack Voter [Maiden]" },
			{ "TX_JACKSON_MA", "TX Jackson Voter [Maiden]" },
			{ "TX_JASPER_MA", "TX Jasper Voter [Maiden]" },
			{ "TX_JEFFDAVIS_MA", "TX Jeff Davis Voter [Maiden]" },
			{ "TX_JEFFERSON_MA", "TX Jefferson Voter [Maiden]" },
			{ "TX_JIMHOGG_MA", "TX Jim Hogg Voter [Maiden]" },
			{ "TX_JIMWELLS_MA", "TX Jim Wells Voter [Maiden]" },
			{ "TX_JOHNSON_MA", "TX Johnson Voter [Maiden]" },
			{ "TX_JONES_MA", "TX Jones Voter [Maiden]" },
			{ "TX_KARNES_MA", "TX Karnes Voter [Maiden]" },
			{ "TX_KAUFMAN_MA", "TX Kaufman Voter [Maiden]" },
			{ "TX_KENDALL_MA", "TX Kendall Voter [Maiden]" },
			{ "TX_KENEDY_MA", "TX Kenedy Voter [Maiden]" },
			{ "TX_KENT_MA", "TX Kent Voter [Maiden]" },
			{ "TX_KERR_MA", "TX Kerr Voter [Maiden]" },
			{ "TX_KIMBLE_MA", "TX Kimble Voter [Maiden]" },
			{ "TX_KING_MA", "TX King Voter [Maiden]" },
			{ "TX_KINNEY_MA", "TX Kinney Voter [Maiden]" },
			{ "TX_KLEBERG_MA", "TX Kleberg Voter [Maiden]" },
			{ "TX_KNOX_MA", "TX Knox Voter [Maiden]" },
			{ "TX_LA_SALLE_MA", "TX La Salle Voter [Maiden]" },
			{ "TX_LAMAR_MA", "TX Lamar Voter [Maiden]" },
			{ "TX_LAMB_MA", "TX Lamb Voter [Maiden]" },
			{ "TX_LAMPASAS_MA", "TX Lampasas Voter [Maiden]" },
			{ "TX_LAVACA_MA", "TX Lavaca Voter [Maiden]" },
			{ "TX_LEE_MA", "TX Lee Voter [Maiden]" },
			{ "TX_LEON_MA", "TX Leon Voter [Maiden]" },
			{ "TX_LIBERTY_MA", "TX Liberty Voter [Maiden]" },
			{ "TX_LIMESTONE_MA", "TX Limestone Voter [Maiden]" },
			{ "TX_LIPSCOMB_MA", "TX Lipscomb Voter [Maiden]" },
			{ "TX_LIVEOAK_MA", "TX Live Oak Voter [Maiden]" },
			{ "TX_LLANO_MA", "TX Llano Voter [Maiden]" },
			{ "TX_LOVING_MA", "TX Loving Voter [Maiden]" },
			{ "TX_LUBBOCK_MA", "TX Lubbock Voter [Maiden]" },
			{ "TX_LYNN_MA", "TX Lynn Voter [Maiden]" },
			{ "TX_MADISON_MA", "TX Madison Voter [Maiden]" },
			{ "TX_MARION_MA", "TX Marion Voter [Maiden]" },
			{ "TX_MARTIN_MA", "TX Martin Voter [Maiden]" },
			{ "TX_MASON_MA", "TX Mason Voter [Maiden]" },
			{ "TX_MATAGORDA_MA", "TX Matagorda Voter [Maiden]" },
			{ "TX_MAVERICK_MA", "TX Maverick Voter [Maiden]" },
			{ "TX_MCCULLOCH_MA", "TX McCulloch Voter [Maiden]" },
			{ "TX_MCLENNAN_MA", "TX McLennan Voter [Maiden]" },
			{ "TX_MCMULLEN_MA", "TX McMullen Voter [Maiden]" },
			{ "TX_MEDINA_MA", "TX Medina Voter [Maiden]" },
			{ "TX_MENARD_MA", "TX Menard Voter [Maiden]" },
			{ "TX_MIDLAND_MA", "TX Midland Voter [Maiden]" },
			{ "TX_MILAM_MA", "TX Milam Voter [Maiden]" },
			{ "TX_MILLS_MA", "TX Mills Voter [Maiden]" },
			{ "TX_MITCHELL_MA", "TX Mitchell Voter [Maiden]" },
			{ "TX_MONTAGUE_MA", "TX Montague Voter [Maiden]" },
			{ "TX_MONTGOMERY_MA", "TX Montgomery Voter [Maiden]" },
			{ "TX_MOORE_MA", "TX Moore Voter [Maiden]" },
			{ "TX_MORRIS_MA", "TX Morris Voter [Maiden]" },
			{ "TX_MOTLEY_MA", "TX Motley Voter [Maiden]" },
			{ "TX_NACOGDOCHES_MA", "TX Nacogdoches Voter [Maiden]" },
			{ "TX_NAVARRO_MA", "TX Navarro Voter [Maiden]" },
			{ "TX_NEWTON_MA", "TX Newton Voter [Maiden]" },
			{ "TX_NOLAN_MA", "TX Nolan Voter [Maiden]" },
			{ "TX_NUECES_MA", "TX Nueces Voter [Maiden]" },
			{ "TX_OCHILTREE_MA", "TX Ochiltree Voter [Maiden]" },
			{ "TX_OLDHAM_MA", "TX Oldham Voter [Maiden]" },
			{ "TX_ORANGE_MA", "TX Orange Voter [Maiden]" },
			{ "TX_PALOPINTO_MA", "TX Palo Pinto Voter [Maiden]" },
			{ "TX_PANOLA_MA", "TX Panola Voter [Maiden]" },
			{ "TX_PARKER_MA", "TX Parker Voter [Maiden]" },
			{ "TX_PARMER_MA", "TX Parmer Voter [Maiden]" },
			{ "TX_PECOS_MA", "TX Pecos Voter [Maiden]" },
			{ "TX_POLK_MA", "TX Polk Voter [Maiden]" },
			{ "TX_POTTER_MA", "TX Potter Voter [Maiden]" },
			{ "TX_PRESIDIO_MA", "TX Presidio Voter [Maiden]" },
			{ "TX_RAINS_MA", "TX Rains Voter [Maiden]" },
			{ "TX_RANDALL_MA", "TX Randall Voter [Maiden]" },
			{ "TX_REAGAN_MA", "TX Reagan Voter [Maiden]" },
			{ "TX_REAL_MA", "TX Real Voter [Maiden]" },
			{ "TX_REDRIVER_MA", "TX Red River Voter [Maiden]" },
			{ "TX_REEVES_MA", "TX Reeves Voter [Maiden]" },
			{ "TX_REFUGIO_MA", "TX Refugio Voter [Maiden]" },
			{ "TX_ROBERTS_MA", "TX Roberts Voter [Maiden]" },
			{ "TX_ROBERTSON_MA", "TX Robertson Voter [Maiden]" },
			{ "TX_ROCKWALL_MA", "TX Rockwall Voter [Maiden]" },
			{ "TX_RUNNELS_MA", "TX Runnels Voter [Maiden]" },
			{ "TX_RUSK_MA", "TX Rusk Voter [Maiden]" },
			{ "TX_SABINE_MA", "TX Sabine Voter [Maiden]" },
			{ "TX_SANAUGUSTINE_MA", "TX San Augustine Voter [Maiden]" },
			{ "TX_SANJACINTO_MA", "TX San Jacinto Voter [Maiden]" },
			{ "TX_SANPATRICIO_MA", "TX San Patricio Voter [Maiden]" },
			{ "TX_SANSABA_MA", "TX San Saba Voter [Maiden]" },
			{ "TX_SCHLEICHER_MA", "TX Schleicher Voter [Maiden]" },
			{ "TX_SCURRY_MA", "TX Scurry Voter [Maiden]" },
			{ "TX_SHACKELFORD_MA", "TX Shackelford Voter [Maiden]" },
			{ "TX_SHELBY_MA", "TX Shelby Voter [Maiden]" },
			{ "TX_SHERMAN_MA", "TX Sherman Voter [Maiden]" },
			{ "TX_SMITH_MA", "TX Smith Voter [Maiden]" },
			{ "TX_SOMERVELL_MA", "TX Somervell Voter [Maiden]" },
			{ "TX_STARR_MA", "TX Starr Voter [Maiden]" },
			{ "TX_STEPHENS_MA", "TX Stephens Voter [Maiden]" },
			{ "TX_STERLING_MA", "TX Sterling Voter [Maiden]" },
			{ "TX_STONEWALL_MA", "TX Stonewall Voter [Maiden]" },
			{ "TX_SUTTON_MA", "TX Sutton Voter [Maiden]" },
			{ "TX_SWISHER_MA", "TX Swisher Voter [Maiden]" },
			{ "TX_TARRANT_MA", "TX Tarrant Voter [Maiden]" },
			{ "TX_TAYLOR_MA", "TX Taylor Voter [Maiden]" },
			{ "TX_TERRELL_MA", "TX Terrell Voter [Maiden]" },
			{ "TX_TERRY_MA", "TX Terry Voter [Maiden]" },
			{ "TX_THROCKMORTON_MA", "TX Throckmorton Voter [Maiden]" },
			{ "TX_TITUS_MA", "TX Titus Voter [Maiden]" },
			{ "TX_TOMGREEN_MA", "TX Tom Green Voter [Maiden]" },
			{ "TX_TRAVIS_MA", "TX Travis Voter [Maiden]" },
			{ "TX_TRINITY_MA", "TX Trinity Voter [Maiden]" },
			{ "TX_TYLER_MA", "TX Tyler Voter [Maiden]" },
			{ "TX_UPSHUR_MA", "TX Upshur Voter [Maiden]" },
			{ "TX_UPTON_MA", "TX Upton Voter [Maiden]" },
			{ "TX_UVALDE_MA", "TX Uvalde Voter [Maiden]" },
			{ "TX_VALVERDE_MA", "TX Val Verde Voter [Maiden]" },
			{ "TX_VANZANDT_MA", "TX Van Zandt Voter [Maiden]" },
			{ "TX_VICTORIA_MA", "TX Victoria Voter [Maiden]" },
			{ "TX_WALKER_MA", "TX Walker Voter [Maiden]" },
			{ "TX_WALLER_MA", "TX Waller Voter [Maiden]" },
			{ "TX_WARD_MA", "TX Ward Voter [Maiden]" },
			{ "TX_WASHINGTON_MA", "TX Washington Voter [Maiden]" },
			{ "TX_WEBB_MA", "TX Webb Voter [Maiden]" },
			{ "TX_WHARTON_MA", "TX Wharton Voter [Maiden]" },
			{ "TX_WHEELER_MA", "TX Wheeler Voter [Maiden]" },
			{ "TX_WICHITA_MA", "TX Wichita Voter [Maiden]" },
			{ "TX_WILBARGER_MA", "TX Wilbarger Voter [Maiden]" },
			{ "TX_WILLACY_MA", "TX Willacy Voter [Maiden]" },
			{ "TX_WILLIAMSON_MA", "TX Williamson Voter [Maiden]" },
			{ "TX_WILSON_MA", "TX Wilson Voter [Maiden]" },
			{ "TX_WINKLER_MA", "TX Winkler Voter [Maiden]" },
			{ "TX_WISE_MA", "TX Wise Voter [Maiden]" },
			{ "TX_WOOD_MA", "TX Wood Voter [Maiden]" },
			{ "TX_YOAKUM_MA", "TX Yoakum Voter [Maiden]" },
			{ "TX_YOUNG_MA", "TX Young Voter [Maiden]" },
			{ "TX_ZAPATA_MA", "TX Zapata Voter [Maiden]" },
			{ "TX_ZAVALA_MA", "TX Zavala Voter [Maiden]" } };

	public static String[][] DRIVERS_LICENCE_NAME_SEARCH_OPTIONS = {
			{ "GRP_DL_NAME", "Search All Items Below" },
			{ "fldl", "Florida Driver" }, { "iddl", "Idaho Driver [old]" },
			{ "IADL_OLD", "Iowa Driver [old]" },
			{ "mndl", "Minnesota Driver [old]" },
			{ "msdl", "Mississippi Driver [old]" },
			{ "ohdl", "Ohio Driver [Old]" }, { "txdl", "Texas Driver" },
			{ "widl", "Wisconsin DL [Old]" } };

	// expand options for DRIVERS LICENCE for each state
	public static String[][] DPPA = {
			{ "", "" },
			{ "DPPA-01", "For any use in the normal course of business..." },
			{ "DPPA-02", "Have subject's written consent for search..." },
			{ "DPPA-03", "For research or statistical activities..." },
			{ "DPPA-04", "For insurance support activity..." },
			{ "DPPA-05", "For towing and impound operators..." },
			{ "DPPA-06", "By a licensed private investigative agency..." },
			{ "DPPA-07", "For employer CDL verification..." },
			{ "DPPA-08", "For private tollway operation..." },
			{ "DPPA-10", "For government agency use..." },
			{ "DPPA-11", "For Court or arbitral proceeding" },
			{ "DPPA-12", "For any use pursuant to an order of a court..." },
			{ "DPPA-13", "Use related to public safety..." },
			{ "DPPA-14", "Use in variety of motor vehicle matters..." },
			{ "DPPA-15",
					"Use in the 'Automobile Information Disclosure Act', the..." } };

	public static String[][] SECRETARY_OF_STATE_CORPORATION_NAME_SEARCH = {
			{ "GRP_SOS_NAME", "Search All Items Below" },
			{ "grp_sos_AL_name", "Alabama Secretary of State" },
			{ "grp_sos_AK_name", "Alaska Secretary of State" },
			{ "grp_sos_AZ_name", "Arizona Secretary of State" },
			{ "grp_sos_AR_name", "Arkansas Secretary of State" },
			{ "grp_sos_CA_name", "California Secretary of State" },
			{ "grp_sos_CO_name", "Colorado Secretary of State" },
			{ "grp_sos_CT_name", "Connecticut Secretary of State" },
			{ "grp_sos_DE_name", "Delaware Secretary of State" },
			{ "grp_sos_FL_name", "Florida Secretary of State" },
			{ "grp_sos_GA_name", "Georgia Secretary of State" },
			{ "grp_sos_HI_name", "Hawaii Secretary of State" },
			{ "grp_sos_ID_name", "Idaho Secretary of State" },
			{ "grp_sos_IL_name", "Illinois Secretary of State" },
			{ "grp_sos_in_name", "Indiana Secretary of State" },
			{ "grp_sos_ia_name", "Iowa Secretary of State" },
			{ "grp_sos_KS_name", "Kansas Secretary of State" },
			{ "grp_sos_KY_name", "Kentucky Secretary of State" },
			{ "grp_sos_la_name", "Louisiana Secretary of State" },
			{ "grp_sos_MD_name", "Maryland Secretary of State" },
			{ "grp_sos_MA_name", "Massachusetts Secretary of State" },
			{ "grp_sos_ME_name", "Maine Secretary of State" },
			{ "grp_sos_mi_name", "Michigan Secretary of State" },
			{ "grp_sos_MN_name", "Minnesota Secretary of State" },
			{ "grp_sos_MS_name", "Mississippi Secretary of State" },
			{ "grp_sos_MO_name", "Missouri Secretary of State" },
			{ "grp_sos_MT_name", "Montana Secretary of State" },
			{ "grp_sos_NE_name", "Nebraska Secretary of State" },
			{ "grp_sos_NV_name", "Nevada Secretary of State" },
			{ "grp_sos_NH_name", "New Hampshire Secretary of State" },
			{ "grp_sos_NM_name", "New Mexico Secretary of State" },
			{ "grp_sos_NY_name", "New York Secretary of State" },
			{ "grp_sos_NC_name", "North Carolina Secretary of State" },
			{ "grp_sos_ND_name", "North Dakota Secretary of State" },
			{ "grp_sos_OH_name", "Ohio Secretary of State" },
			{ "grp_sos_OR_name", "Oregon Secretary of State" },
			{ "grp_sos_PA_name", "Pennsylvania Secretary of State" },
			{ "grp_sos_RI_name", "Rhode Island Secretary of State" },
			{ "grp_sos_SC_name", "South Carolina Secretary of State" },
			{ "grp_sos_SD_name", "South Dakota Secretary of State" },
			{ "grp_sos_TN_name", "Tennessee Secretary of State" },
			{ "grp_sos_UT_name", "Utah Secretary of State" },
			{ "grp_sos_VT_name", "Vermont Secretary of State" },
			{ "grp_sos_WA_name", "Washington Secretary of State" },
			{ "grp_sos_WV_name", "West Virginia Secretary of State" },
			{ "grp_sos_wi_name", "Wisconsin Secretary of State" },
			{ "grp_sos_WY_name", "Wyoming Secretary of State" } };
	// expand Secretary of state counties

	public static String[][] PROFESSIONAL_LICENSE_NAME_SEARCH_OPTIONS = {
			{ "GRP_PL_NAME", "Search All Items Below" },
			{ "GRP_PL_AL_NAME", "Alabama Professional License" },
			{ "GRP_PL_AK_NAME", "Alaska Professional License" },
			{ "GRP_PL_AZ_NAME", "Arizona Professional License" },
			{ "GRP_PL_AR_NAME", "Arkansas Professional License" },
			{ "GRP_PL_CA_NAME", "California Professional License" },
			{ "GRP_PL_CO_NAME", "Colorado Professional License" },
			{ "GRP_PL_CT_NAME", "Connecticut Professional License" },
			{ "GRP_PL_DE_NAME", "Delaware Professional License" },
			{ "GRP_PL_DC_NAME", "District of Columbia Professional License" },
			{ "GRP_PL_FL_NAME", "Florida Professional License" },
			{ "GRP_PL_GA_NAME", "Georgia Professional License" },
			{ "GRP_PL_HI_NAME", "Hawaii Professional License" },
			{ "GRP_PL_ID_NAME", "Idaho Professional License" },
			{ "GRP_PL_IL_NAME", "Illinois Professional License" },
			{ "GRP_PL_IN_NAME", "Indiana Professional License" },
			{ "GRP_PL_IA_NAME", "Iowa Professional License" },
			{ "GRP_PL_KS_NAME", "Kansas Professional License" },
			{ "GRP_PL_KY_NAME", "Kentucky Professional License" },
			{ "GRP_PL_LA_NAME", "Louisiana Professional License" },
			{ "GRP_PL_ME_NAME", "Maine Professional License" },
			{ "GRP_PL_MD_NAME", "Maryland Professional License" },
			{ "GRP_PL_MA_NAME", "Massachusetts Professional License" },
			{ "GRP_PL_MI_NAME", "Michigan Professional License" },
			{ "GRP_PL_MN_NAME", "Minnesota Professional License" },
			{ "GRP_PL_MS_NAME", "Mississippi Professional License" },
			{ "GRP_PL_MO_NAME", "Missouri Professional License" },
			{ "GRP_PL_MT_NAME", "Montana Professional License" },
			{ "GRP_PL_NE_NAME", "Nebraska Professional License" },
			{ "GRP_PL_NV_NAME", "Nevada Professional License" },
			{ "GRP_PL_NH_NAME", "New Hampshire Professional License" },
			{ "GRP_PL_NJ_NAME", "New Jersey Professional License" },
			{ "GRP_PL_NM_NAME", "New Mexico Professional License" },
			{ "GRP_PL_NY_NAME", "New York Professional License" },
			{ "GRP_PL_NC_NAME", "North Carolina Professional License" },
			{ "GRP_PL_ND_NAME", "North Dakota Professional License" },
			{ "GRP_PL_OH_NAME", "Ohio Professional License" },
			{ "GRP_PL_OK_NAME", "Oklahoma Professional License" },
			{ "GRP_PL_OR_NAME", "Oregon Professional License" },
			{ "GRP_PL_PA_NAME", "Pennsylvania Professional License" },
			{ "GRP_PL_RI_NAME", "Rhode Island Professional License" },
			{ "GRP_PL_SC_NAME", "South Carolina Professional License" },
			{ "GRP_PL_SD_NAME", "South Dakota Professional License" },
			{ "GRP_PL_TN_NAME", "Tennessee Professional License" },
			{ "GRP_PL_TX_NAME", "Texas Professional License" },
			{ "GRP_PL_UT_NAME", "Utah Professional License" },
			{ "GRP_PL_VT_NAME", "Vermont Professional License" },
			{ "GRP_PL_VA_NAME", "Virginia Professional License" },
			{ "GRP_PL_WA_NAME", "Washington Professional License" },
			{ "GRP_PL_WV_NAME", "West Virginia Professional License" },
			{ "GRP_PL_WI_NAME", "Wisconsin Professional License" },
			{ "GRP_PL_WY_NAME", "Wyoming Professional License" } };

	// expand options for PROFFESSIONAL LICENSE for each state
	public static String[][] PROFESSIONAL_LICENSE_NAME_SEARCH_TX = {
			{ "GRP_PL_TX_NAME", "Search All Items Below" },
			{ "TX_PRO_AC_TECH_CERT", "Texas A/C Technicians - Certified" },
			{ "TX_PRO_AC_TECH_CERT", "Texas A/C Technicians - Certified" },
			{ "TX_PRO_AC_TECH_REG", "Texas A/C Technicians - Registered" },
			{ "TX_PRO_ACCESS", "Texas Accessibility Specialists" },
			{ "TX_PRO_ACUPUNCTURIST", "Texas Acupuncturists" },
			{ "TX_PRO_ADV_PRAC_NURS", "Texas Advanced Practice Nurses" },
			{ "TX_PRO_AIR_CONT", "Texas Air Conditioning Contractors" },
			{ "TX_PRO_ALCOHOL", "Texas Alcoholic Beverage" },
			{ "tx_pro_alco_edu_prog", "Texas Alcohol Education Programs" },
			{ "TX_PRO_APPRAISER", "Texas Appraisers" },
			{ "TX_PRO_ARCHITECT", "Texas Architects" },
			{ "TX_PRO_ARCHTECT_EMER", "Texas Architects - Emeritus" },
			{ "TX_PRO_ASS_AUCT", "Texas Associate Auctioneers" },
			{ "TX_PRO_ATH_TRAIN", "Texas Athletic Trainers" },
			{ "TX_PRO_ATH_TRAIN_TMP", "Texas Athletic Trainers - Temp." },
			{ "TX_PRO_ATTORNEY", "Texas Attorneys" },
			{ "TX_PRO_AUCTIONEER", "Texas Auctioneers" },
			{ "TX_PRO_AUDIO", "Texas Audiologists" },
			{ "TX_PRO_AUDIOL_ASST", "Texas Audiologist Assistants" },
			{ "TX_PRO_AUDIO_INTERN", "Texas Audiologist Interns" },
			{ "TX_PRO_BARBER_MANI", "Texas Barber Manicurists" },
			{ "TX_PRO_BARBER_TEACH", "Texas Barber Teachers" },
			{ "TX_PRO_BARBER_TECH", "Texas Barber Technicians" },
			{ "tx_pro_barber", "Texas Barbers (Class A)" },
			{ "TX_PRO_BARBER_HBRAID",
					"Texas Barbers - Hair Braiding Specialists" },
			{ "TX_PRO_BARB_BTH_BARB", "Texas Barber Booth Rentals - Barbers" },
			{ "TX_PRO_BARB_BTH_HAIR",
					"Texas Barber Booth Rentals - Hair Braiding " },
			{ "TX_PRO_BARB_BTH_MANI",
					"Texas Barber Booth Rentals - Manicurists" },
			{ "tx_pro_barber_shop", "Texas Barber Shops - Barbers" },
			{ "TX_PRO_BARBER_SHOP_B", "Texas Barber Shops - Hair Braiding" },
			{ "TX_PRO_BARBER_SHOP_W", "Texas Barber Shops - Hair Weaving" },
			{ "TX_PRO_BARBER_SHOP_M", "Texas Barber Shops - Manicurists" },
			{ "tx_pro_booting_co", "Texas Booting Companies" },
			{ "tx_pro_booting_op", "Texas Booting Operators" },
			{ "grp_pl_TX_name_box", "Texas Boxing Licenses" },
			{ "TX_PRO_BOXER", "Texas Boxing - Fist Boxers" },
			{ "TX_PRO_BOX_JUDGE", "Texas Boxing - Judges" },
			{ "TX_PRO_BOX_MAN", "Texas Boxer/Wrestler Managers" },
			{ "TX_PRO_BOX_MATCH", "Texas Boxing - Matchmakers" },
			{ "TX_PRO_BOX_PROM", "Texas Boxing - Promoters" },
			{ "TX_PRO_BOX_REF", "Texas Boxing and Wrestling Referees" },
			{ "TX_PRO_BOX_SEC", "Texas Boxing - Seconds" },
			{ "TX_PRO_BOX_TIME", "Texas Boxing - Timekeepers" },
			{ "TX_PRO_CPA_FIRM", "Texas Accountant Firms" },
			{ "TX_PRO_CPA", "Texas Accountants" },
			{ "TX_PRO_CHECK_VERIFIC", "Texas Check Verification Entities" },
			{ "TX_PRO_CHEM_DEP_COUN",
					"Texas Licensed Chemical Dependency Counselors - CI" },
			{ "tx_pro_chem_dep_co_i",
					"Texas Chemical Dependency Counselor Interns" },
			{ "tx_pro_chem_dep_lcdc",
					"Texas Licensed Chemical Dependency Counselors - LCDC" },
			{ "tx_pro_lcdc_cti",
					"Texas Chemical Dependency Counselor Clinical Training Institute Permits" },
			{ "tx_pro_lcdc_cepro",
					"Texas Chemical Dependency Counselor CE Providers" },
			{ "TX_PRO_CHIROPRACTOR", "Texas Chiropractors" },
			{ "TX_PRO_CODE_EFF_OFCR", "Texas Code Enforcement - Officers" },
			{ "TX_PRO_CODE_EFF_OINT",
					"Texas Code Enforcement - Officers In Training" },
			{ "TX_PRO_CONTACT_IND",
					"Texas Contact Lens Dispensers - Individuals" },
			{ "TX_PRO_CONTACT_ORG", "Texas Contact Lens Dispensers - Org." },
			{ "tx_pro_access_ce_prv",
					"Texas Continuing Education Providers for Registered Accessibility Specialists" },
			{ "TX_PRO_CE_PROV_AC",
					"Texas Continuing Education Providers for A/C Contractors" },
			{ "tx_pro_auctioneer_ce",
					"Texas Continuing Education Providers for Auctioneers" },
			{ "tx_pro_cosmetol_ce",
					"Texas Continuing Education Providers for Cosmetology" },
			{ "tx_pro_court_int_ce",
					"Texas Continuing Education Providers for Licensed Court Interpreters" },
			{ "tx_pro_ce_provider",
					"Texas Continuing Education Providers for Electricians" },
			{ "tx_pro_prop_tax_ce",
					"Texas Continuing Education Providers for Property Tax Consultants" },
			{ "tx_pro_ce_prov_prop",
					"Texas Continuing Education Providers for Property Tax Professionals" },
			{ "tx_pro_tow_op_ce_prv",
					"Texas Continuing Education Providers for Tow Operators" },
			{
					"tx_pro_well_drill_ce",
					"Texas Continuing Education Providers for Water Well Drillers and Pump Installers" },
			{ "tx_pro_cosmetologist", "Texas Cosmetology - Operators" },
			{ "TX_PRO_COSM_BR_FACI",
					"Texas Cosmetology - Booth Rentals Facial Instructors" },
			{ "TX_PRO_COSM_BR_FACT",
					"Texas Cosmetology - Booth Rentals Facialists" },
			{ "TX_PRO_COSM_BR_HBRD",
					"Texas Cosmetology - Booth Rentals Hair Braiding Instructors" },
			{ "TX_PRO_COSM_BR_HWEA",
					"Texas Cosmetology - Booth Rentals Hair Weavers" },
			{ "TX_PRO_COSM_BR_MANI",
					"Texas Cosmetology - Booth Rentals Manicure Instructors" },
			{ "TX_PRO_COSM_BR_MANT",
					"Texas Cosmetology - Booth Rentals Manicurists" },
			{ "TX_PRO_COSM_BR_OPER",
					"Texas Cosmetology - Booth Rentals Operators" },
			{ "TX_PRO_COSM_BR_OPIN",
					"Texas Cosmetology - Booth Rentals Operator Instructor " },
			{ "TX_PRO_COSM_BR_WIG", "Texas Cosmetology - Booth Rentals Wig" },
			{ "TX_PRO_DUAL_SHOPS", "Texas Cosmetology - Dual Shops" },
			{ "TX_PRO_COSM_FAC_INST", "Texas Cosmetology - Facial Instructors" },
			{ "TX_PRO_COSM_FAC_SPEC", "Texas Cosmetology - Facial Specialists" },
			{ "TX_PRO_COSM_HAIR_WEA",
					"Texas Cosmetology - Hair Weaving Braiding Specialists" },
			{ "TX_PRO_COSM_MANI_INS",
					"Texas Cosmetology - Manicurist Instructors" },
			{ "TX_PRO_COSM_OP_INST", "Texas Cosmetology - Operator Instructors" },
			{ "tx_pro_cosmet_salon", "Texas Cosmetology Salons - Beauty" },
			{ "TX_PRO_COSMET_SAL_FA", "Texas Cosmetology Salons - Facial" },
			{ "TX_PRO_COSMET_SAL_FM",
					"Texas Cosmetology Salons - Facial and Manicure" },
			{ "TX_PRO_COSMET_SAL_HB",
					"Texas Cosmetology Salons - Hair Braiding" },
			{ "TX_PRO_COSMET_SAL_HW",
					"Texas Cosmetology Salons - Hair Weaving and Braiding" },
			{ "TX_PRO_COSMET_SAL_MA", "Texas Cosmetology Salons - Manicure" },
			{ "TX_PRO_COSMET_SAL_WI", "Texas Cosmetology Salons - Wig" },
			{ "TX_PRO_COSM_SCHL_JC",
					"Texas Cosmetology Schools - Junior College" },
			{ "TX_PRO_COSM_SCHL_PS",
					"Texas Cosmetology Schools - Private School" },
			{ "TX_PRO_COSM_SCHL_VHS",
					"Texas Cosmetology Schools - Vocational High School" },
			{ "TX_PRO_COSM_SHAMPOO", "Texas Cosmetology - Shampoo Specialists" },
			{ "TX_PRO_COSM_WIG_INST", "Texas Cosmetology - Wig Instructors" },
			{ "TX_PRO_COSM_WIG_SPEC", "Texas Cosmetology - Wig Specialists" },
			{ "tx_pro_coun_ce_prov", "Texas Counselor CE Providers" },
			{ "TX_PRO_COUN_SUPR", "Texas Counselor Supervisors" },
			{ "tx_pro_counselor", "Texas Counselors" },
			{ "TX_PRO_COUNSELOR_INT", "Texas Counselor Interns" },
			{ "TX_PRO_COURT_INT", "Texas Licensed Court Interpreters" },
			{ "TX_PRO_DENT_ASST", "Texas Dental Assistants" },
			{ "TX_PRO_DENT_HYG", "Texas Dental Hygienists" },
			{ "TX_PRO_DENT_LAB", "Texas Dental Laboratories" },
			{ "TX_PRO_DENTIST", "Texas Dentists" },
			{ "TX_PRO_DIETICIAN", "Texas Dietitians" },
			{ "TX_PRO_DIETITIAN_PRV", "Texas Dietitians - Provisional" },
			{ "TX_PRO_DISC_HLTH_CAR", "Texas Discount Health Care Operators" },
			{ "tx_pro_drug_off_educ", "Texas Drug Offender Education Programs" },
			{ "tx_pro_educators", "Texas Educators" },
			{ "grp_pl_TX_name_elec", "Texas Electrician Licenses" },
			{ "TX_PRO_ELEC_CONT", "Texas Electrical Contractors" },
			{ "TX_PRO_ELEC_SCONT", "Texas Electrical Sign Contractors" },
			{ "TX_PRO_ELEC_APPR", "Texas Apprentice Electricians" },
			{ "TX_PRO_ELEC_JOUR", "Texas Journeyman Electricians" },
			{ "TX_PRO_ELEC_JSIGN", "Texas Journeyman Sign Electricians" },
			{ "TX_PRO_ELEC_MAINT", "Texas Maintenance Electricians" },
			{ "TX_PRO_ELEC_MAST", "Texas Master Electricians" },
			{ "TX_PRO_ELEC_MSIGN", "Texas Master Sign Electricians" },
			{ "TX_PRO_ELEC_RWIRE", "Texas Electricians - Residential Wiremen" },
			{ "TX_PRO_EMER_JOUR_ELE", "Texas Emergency Journeyman Electricians" },
			{ "TX_PRO_EMER_MAST_ELE", "Texas Emergency Master Electricians" },
			{ "TX_PRO_EMER_MAST_SIG",
					"Texas Emergency Master Sign Electricians" },
			{ "TX_PRO_ELEV_CONT", "Texas Elevator Contractors" },
			{ "TX_PRO_ELEV_INSP", "Texas Elevator Inspectors" },
			{ "tx_pro_ems_ce_prog", "Texas EMS CE Programs" },
			{ "tx_pro_ems_education", "Texas EMS Education" },
			{ "tx_pro_ems_first_res", "Texas EMS First Responders" },
			{ "tx_pro_ems_provider", "Texas EMS Providers" },
			{ "TX_PRO_FORN_BANK_AGC", "Texas Foreign Bank Agencies" },
			{ "TX_PRO_FORN_BANK_BRA", "Texas Foreign Bank Branches" },
			{ "TX_PRO_FORN_BANK_REP",
					"Texas Foreign Bank Representative Offices" },
			{ "TX_PRO_FREON",
					"Texas Certificate of Registrations to Purchase Freon" },
			{ "tx_pro_funeral_dir", "Texas Funeral Directors and Embalmers" },
			{ "tx_pro_grad_nurse", "Texas Graduate Nurses" },
			{ "TX_PRO_HEAR_AID_DISP",
					"Texas Hearing Aid Fitters and Dispensers" },
			{ "TX_PRO_HEAR_AID_DAPP",
					"Texas Hearing Aid Fitters and Dispensers - Apprentice" },
			{ "TX_PRO_HEAR_AID_CE_M",
					"Texas Hearing Aid Fitters and Dispensers - CE Manufacturer" },
			{ "TX_PRO_HEAR_AID_CE_N",
					"Texas Hearing Aid Fitters and Dispensers - CE Non-Manufacturer" },
			{ "TX_PRO_HEAR_AID_TEMP",
					"Texas Hearing Aid Fitters and Dispensers - Temp." },
			{ "TX_PRO_INS_AGCY", "Texas Insurance Agencies" },
			{ "TX_PRO_INS_AGENT", "Texas Insurance Agents" },
			{ "TX_PRO_INT_DESIGN", "Texas Interior Designers" },
			{ "TX_PRO_LAND_SURV", "Texas Land Surveyors - Registered" },
			{ "TX_PRO_LAND_SURV_LIC", "Texas Land Surveyors - Licensed" },
			{ "TX_PRO_LAND_ARCH", "Texas Landscape Architects" },
			{ "TX_PRO_LEGAL_COMP", "Texas Legal Service Contracts" },
			{ "TX_PRO_FUNERAL_HOME", "Texas Licensed Funeral Homes" },
			{ "TX_PRO_LIC_VOC_NURSE", "Texas Licensed Vocational Nurses" },
			{ "tx_pro_manicurist", "Texas Cosmetology - Manicurists" },
			{ "TX_PRO_MFT", "Texas Marriage and Family Therapists" },
			{ "tx_pro_marr_fam_asso",
					"Texas Marriage and Family Therapist Associates" },
			{ "TX_PRO_MFT_CE_PROV",
					"Texas Marriage and Family Therapists - CE Providers" },
			{ "TX_PRO_MFT_SUPER",
					"Texas Marriage and Family Therapists - Supervisors" },
			{ "TX_PRO_MASS_THER", "Texas Massage Therapists" },
			{ "TX_PRO_MASSAGE_CEPRV", "Texas Massage Therapy CE Providers" },
			{ "TX_PRO_MASSAGE_ESTAB", "Texas Massage Therapy Establishments" },
			{ "TX_PRO_MASSAGE_INST", "Texas Massage Therapy Instructors" },
			{ "TX_PRO_MASSAGE_SCHL", "Texas Massage Therapy Schools" },
			{ "TX_PRO_MED_PHYS", "Texas Physicists" },
			{ "TX_PRO_MIDWIFE", "Texas Midwives" },
			{ "TX_PRO_MONEY_SERVICE", "Texas Money Services Businesses" },
			{ "TX_PRO_OCCU_THER", "Texas Occupational Therapist" },
			{ "TX_PRO_OCCU_FACIL", "Texas Occupational Therapy Facilities" },
			{ "TX_PRO_OPTICIAN_CONT", "Texas Opticians - Contacts" },
			{ "TX_PRO_OPTICIAN_DUAL", "Texas Opticians - Dual" },
			{ "TX_PRO_OPTICIAN_SPEC", "Texas Opticians - Spectacles" },
			{ "TX_PRO_OPTOMETRIST", "Texas Optometrists" },
			{ "TX_PRO_ORTHOTIC_FACI",
					"Texas Orthotics and Prosthetics Facilities" },
			{ "tx_pro_orthotist", "Texas Orthotists and Prosthetists" },
			{ "TX_PRO_ORTHOTIST_AST",
					"Texas Orthotists And Prosthetists - Assistants" },
			{ "tx_pro_orth_pros_stu",
					"Texas Orthotist and Prosthetist Students" },
			{ "tx_pro_orth_pros_tmp",
					"Texas Orthotists and Prosthetists - Temporary" },
			{ "TX_PRO_ORTHOTICS_TEC",
					"Texas Orthotists and Prosthetists - Technicians" },
			{ "TX_PRO_PERP_CARE_CEM", "Texas Perpetual Care Cemeteries" },
			{ "TX_PRO_PERFUSION", "Texas Perfusionists" },
			{ "tx_pro_perfusion_prv",
					"Texas Perfusionists - Provisionally Licensed" },
			{ "TX_PRO_PERS_EMER_LIC",
					"Texas Personal Emergency Response System Licenses" },
			{ "TX_PRO_PERS_EMER_REG",
					"Texas Personal Emergency Response System Registrations" },
			{ "TX_PRO_EMPLOY", "Texas Personnel Employment Services" },
			{ "TX_PRO_PHARMACY", "Texas Pharmacies" },
			{ "TX_PRO_PHARMACIST", "Texas Pharmacists" },
			{ "TX_PRO_PHARM_INT", "Texas Pharmacy Interns" },
			{ "TX_PRO_PHARMACY_TECH", "Texas Pharmacy Technicians" },
			{ "TX_PRO_PHYS_THER", "Texas Physical Therapists" },
			{ "TX_PRO_PHYS_FAC", "Texas Physical Therapy Facilities" },
			{ "TX_PRO_PHYS_ASST", "Texas Physician Assistants" },
			{ "TX_PRO_PHYSICIAN", "Texas Physicians" },
			{ "TX_PRO_PHYSICIST_TMP", "Texas Physicists - Temporary" },
			{ "tx_pro_plumbing", "Texas Plumbing" },
			{ "TX_PRO_PROCESS_SERVE", "Texas Process Servers" },
			{ "TX_PRO_PODIATRIST", "Texas Podiatrists" },
			{ "tx_pro_polygraph_exa", "Texas Polygraph Examiners" },
			{ "tx_pro_polygraph_trn", "Texas Polygraph Trainees" },
			{ "TX_PRO_PRE_FUNRL", "Texas Prepaid Funeral Contract Sellers" },
			{ "TX_PRO_PRIV_CHIL_SUP",
					"Texas Private Child Support Enforcement Agencies" },
			{ "TX_PRO_ENGR_FIRM", "Texas Engineer Companies" },
			{ "TX_PRO_ENGR", "Texas Engineers" },
			{ "TX_PRO_EIT", "Texas Engineer Interns" },
			{ "TX_PRO_PROP_TAX", "Texas Property Tax Consultants" },
			{ "tx_pro_prop_tax_appr", "Texas Property Tax Appraisers" },
			{ "tx_pro_prop_tax_asse", "Texas Property Tax Assessors" },
			{ "tx_pro_prop_tax_coll", "Texas Property Tax Collectors" },
			{ "tx_pro_prop_tax_core",
					"Texas Property Tax Professional Core Education Providers" },
			{ "TX_PRO_RADIOL_TECH", "Texas Radiology Technicians" },
			{ "TX_PRO_RADIOL_HDSHIP",
					"Texas Radiology Technicians - Hardship Exemption" },
			{ "TX_PRO_RADIOL_LTD", "Texas Radiology Technicians - Limited" },
			{ "TX_PRO_RADIOL_LTMP",
					"Texas Radiology Technicians - Limited Temp." },
			{ "TX_PRO_RADIOL_NONCRT",
					"Texas Radiology Technicians - Non-Certified" },
			{ "TX_PRO_RADIOL_TEMP", "Texas Radiology Technicians - Temp." },
			{ "TX_PRO_REAL", "Texas Real Estate" },
			{ "TX_PRO_REAL_EST_INSP", "Texas Real Estate Inspectors" },
			{ "tx_pro_re_right_way", "Texas Real Estate Right-of-Way" },
			{ "TX_PRO_REG_NURSE", "Texas Registered Nurses" },
			{ "TX_PRO_REP_TRUST_OFC", "Texas Representative Trust Offices" },
			{ "TX_PRO_RES_APPL_CONT",
					"Texas Residential Appliance Installation Contractors" },
			{ "TX_PRO_RES_APPL_INST", "Texas Residential Appliance Installers" },
			{ "TX_PRO_RESP_CARE", "Texas Respiratory Care Practitioners" },
			{ "TX_PRO_RESP_CARE_TMP", "Texas Respiratory Care Temporary" },
			{ "TX_PRO_RINGSIDE_PHYS", "Texas Ringside Physicians" },
			{ "tx_pro_sanitarian", "Texas Sanitarians" },
			{ "tx_pro_sanitarian_tr", "Texas Sanitarians In Training" },
			{ "TX_PRO_SERVICE", "Texas Service Contract Providers" },
			{ "tx_pro_sxo_edu_prog", "Texas Sex Offender Education Programs" },
			{ "tx_pro_sxo_intv_prog",
					"Texas Sex Offender Intervention Programs" },
			{ "tx_pro_sxo_treatment", "Texas Sex Offender Treatment Providers" },
			{ "TX_PRO_SOCIAL_ADVP",
					"Texas Social Workers - Advanced Practitioner" },
			{ "TX_PRO_SOCIAL_BACCA", "Texas Social Workers - Baccalaureat" },
			{ "TX_PRO_SOCIAL_CEPROV", "Texas Social Workers - CE Providers" },
			{ "TX_PRO_SOC_WORK_CLIN", "Texas Social Workers - Clinical" },
			{ "tx_pro_social_work", "Texas Social Workers - Master" },
			{ "tx_pro_soci_work_ind",
					"Texas Social Workers - Independent Practice" },
			{ "TX_PRO_SOCIAL_SUPER", "Texas Social Workers - Supervisors" },
			{ "TX_PRO_SOCIAL_TEMP", "Texas Social Workers - Temporary" },
			{ "TX_PRO_SPEECH_ASST",
					"Texas Speech Language Pathologist Assistants" },
			{ "TX_PRO_SPEECH_INTERN",
					"Texas Speech Language Pathologist Interns" },
			{ "TX_PRO_SPEECH", "Texas Speech Language Pathologists" },
			{ "TX_PRO_STAFF", "Texas Staff Leasing Services - Regular License" },
			{ "tx_pro_staff_ltd",
					"Texas Staff Leasing Services - Limited License" },
			{ "TX_PRO_STATE_BANK", "Texas State Banks" },
			{ "TX_PRO_TALENT", "Texas Talent Agencies" },
			{ "TX_PRO_TEMP_COMM", "Texas Temporary Common Workers Employers" },
			{ "tx_pro_temp_nurse", "Texas Temporary Nurses" },
			{ "TX_PRO_TOW_TRK_CT", "Texas Tow Truck Operators - CT" },
			{ "TX_PRO_TOW_TRK_IM", "Texas Tow Truck Operators - IM" },
			{ "TX_PRO_TOW_TRK_PP", "Texas Tow Truck Operators - PP" },
			{ "TX_PRO_TRUST_COMPANY", "Texas Trust Companies" },
			{ "tx_pro_used_auto_rec", "Texas Used Auto Parts Recyclers" },
			{ "tx_pro_used_auto_emp",
					"Texas Used Auto Parts Recycler Employees" },
			{ "TX_PRO_VEH_STOR_FACL",
					"Texas Vehicle Storage Facility Employees" },
			{ "tx_pro_vet", "Texas Veterinarians" },
			{ "TX_PRO_WELL_INST", "Texas Water Well Drillers Pump Installers" },
			{ "TX_PRO_WELL_APPR", "Texas Water Well Pump Installer Apprentices" } };

	// name=o_value= ,name=_value=Please select a search
	// type,name=GRP_CIV_NAME_value=Civil Court Name
	// Search,name=GRP_MW_NAME_value=Most Wanted Name
	// Search,name=GRP_SXO_NAME_value=Sex Offender Name
	// Search,name=GRP_CRI_NAME_value=Criminal Name
	// Search,name=GRP_TERROR_KB_NAME_value=Terrorism Knowledge
	// Base,name=GRP_VOTER_NAME_value=Voter Name
	// Search,name=GRP_DL_NAME_value=Driver's License Name
	// Search,name=GRP_SOS_NAME_value=Secretary of State Corporation Name
	// Search,name=grp_pl_name_value=Professional License Name Search - Select
	// Data Source,name=grp_cad_name_value=Property Tax Name Search

	public static String[][] TAX_SEARCH_NAME_SEARCH_OPTIONS = {
			{ "grp_cad_name", "Search All Items Below" },
			{ "grp_cad_FL_name", "Florida Property Tax" },
			{ "grp_cad_ME_name", "Maine Property Tax" },
			{ "grp_cad_ma_name", "Massachusetts Property Tax" },
			{ "grp_cad_NJ_name", "New Jersey Property Tax" },
			{ "grp_cad_NM_name", "New Mexico Property Tax" },
			{ "grp_cad_NY_name", "New York Property Tax" },
			{ "grp_cad_TX_name", "Texas Property Tax" },
			{ "grp_cad_VT_name", "Vermont Property Tax" },
			{ "grp_cad_WV_name", "West Virginia Property Tax" } };

	public static String[][] TAX_SEARCH_NAME_SEARCH_TX = {
			{ "GRP_CAD_TX_NAME", "Search All Items Below" },
			{ "TX_ANDERSON_AND", "TX Anderson CAD" },
			{ "TX_ANDREWS_AND", "TX Andrews CAD" },
			{ "TX_ANGELINA_AND", "TX Angelina CAD" },
			{ "TX_ARANSAS_AND", "TX Aransas CAD" },
			{ "TX_ARCHER_AND", "TX Archer CAD" },
			{ "TX_ARMSTRONG_AND", "TX Armstrong CAD" },
			{ "TX_ATASCOSA_AND", "TX Atascosa CAD" },
			{ "TX_AUSTIN_AND", "TX Austin CAD" },
			{ "TX_BAILEY_AND", "TX Bailey CAD" },
			{ "TX_BANDERA_AND", "TX Bandera CAD" },
			{ "TX_BASTROP_AND", "TX Bastrop CAD" },
			{ "TX_BAYLOR_AND", "TX Baylor CAD" },
			{ "TX_BEE_AND", "TX Bee CAD" }, { "TX_BELL_AND", "TX Bell CAD" },
			{ "TX_BEXAR_AND", "TX Bexar CAD" },
			{ "TX_BLANCO_AND", "TX Blanco CAD" },
			{ "TX_BORDEN_AND", "TX Borden CAD" },
			{ "TX_BOSQUE_AND", "TX Bosque CAD" },
			{ "TX_BOWIE_AND", "TX Bowie CAD" },
			{ "TX_BRAZORIA_AND", "TX Brazoria CAD" },
			{ "TX_BRAZOS_AND", "TX Brazos CAD" },
			{ "TX_BREWSTER_AND", "TX Brewster CAD" },
			{ "TX_BRISCOE_AND", "TX Briscoe CAD" },
			{ "TX_BROOKS_AND", "TX Brooks CAD" },
			{ "TX_BROWN_AND", "TX Brown CAD" },
			{ "TX_BURLESON_AND", "TX Burleson CAD" },
			{ "TX_BURNET_AND", "TX Burnet CAD" },
			{ "TX_CALDWELL_AND", "TX Caldwell CAD" },
			{ "TX_CALHOUN_AND", "TX Calhoun CAD" },
			{ "TX_CALLAHAN_AND", "TX Callahan CAD" },
			{ "TX_CAMERON_AND", "TX Cameron CAD" },
			{ "TX_CAMP_AND", "TX Camp CAD" },
			{ "TX_CARSON_AND", "TX Carson CAD" },
			{ "TX_CASS_AND", "TX Cass CAD" },
			{ "TX_CASTRO_AND", "TX Castro CAD" },
			{ "TX_CHAMBERS_AND", "TX Chambers CAD" },
			{ "TX_CHEROKEE_AND", "TX Cherokee CAD" },
			{ "TX_CHILDRESS_AND", "TX Childress CAD" },
			{ "TX_CLAY_AND", "TX Clay CAD" },
			{ "TX_COCHRAN_AND", "TX Cochran CAD" },
			{ "TX_COKE_AND", "TX Coke CAD" },
			{ "TX_COLEMAN_AND", "TX Coleman CAD" },
			{ "TX_COLLIN_AND", "TX Collin CAD" },
			{ "TX_COLLINGSWORTH_AND", "TX Collingsworth CAD" },
			{ "TX_COLORADO_AND", "TX Colorado CAD" },
			{ "TX_COMAL_AND", "TX Comal CAD" },
			{ "TX_COMANCHE_AND", "TX Comanche CAD" },
			{ "TX_CONCHO_AND", "TX Concho CAD" },
			{ "TX_COOKE_AND", "TX Cooke CAD" },
			{ "TX_CORYELL_AND", "TX Coryell CAD" },
			{ "TX_COTTLE_AND", "TX Cottle CAD" },
			{ "TX_CRANE_AND", "TX Crane CAD" },
			{ "TX_CROCKETT_AND", "TX Crockett CAD" },
			{ "TX_CROSBY_AND", "TX Crosby CAD" },
			{ "TX_CULBERSON_AND", "TX Culberson CAD" },
			{ "TX_DALLAM_AND", "TX Dallam CAD" },
			{ "TX_DALLAS_AND", "TX Dallas CAD" },
			{ "TX_DAWSON_AND", "TX Dawson CAD" },
			{ "TX_DEAF_SMITH_AND", "TX Deaf Smith CAD" },
			{ "TX_DELTA_AND", "TX Delta CAD" },
			{ "TX_DENTON_AND", "TX Denton CAD" },
			{ "TX_DEWITT_AND", "TX DeWitt CAD" },
			{ "TX_DICKENS_AND", "TX Dickens CAD" },
			{ "TX_DIMMIT_AND", "TX Dimmit CAD" },
			{ "TX_DONLEY_AND", "TX Donley CAD" },
			{ "TX_DUVAL_AND", "TX Duval CAD" },
			{ "TX_EASTLAND_AND", "TX Eastland CAD" },
			{ "TX_ECTOR_AND", "TX Ector CAD" },
			{ "TX_EDWARDS_AND", "TX Edwards CAD" },
			{ "TX_EL_PASO_AND", "TX El Paso CAD" },
			{ "TX_ELLIS_AND", "TX Ellis CAD" },
			{ "TX_ERATH_AND", "TX Erath CAD" },
			{ "TX_FALLS_AND", "TX Falls CAD" },
			{ "TX_FANNIN_AND", "TX Fannin CAD" },
			{ "TX_FAYETTE_AND", "TX Fayette CAD" },
			{ "TX_FISHER_AND", "TX Fisher CAD" },
			{ "TX_FLOYD_AND", "TX Floyd CAD" },
			{ "TX_FOARD_AND", "TX Foard CAD" },
			{ "TX_FORT_BEND_AND", "TX Fort Bend CAD" },
			{ "TX_FRANKLIN_AND", "TX Franklin CAD" },
			{ "TX_FREESTONE_AND", "TX Freestone CAD" },
			{ "TX_FRIO_AND", "TX Frio CAD" },
			{ "TX_GAINES_AND", "TX Gaines CAD" },
			{ "TX_GALVESTON_AND", "TX Galveston CAD" },
			{ "TX_GARZA_AND", "TX Garza CAD" },
			{ "TX_GILLESPIE_AND", "TX Gillespie CAD" },
			{ "TX_GLASSCOCK_AND", "TX Glasscock CAD" },
			{ "TX_GOLIAD_AND", "TX Goliad CAD" },
			{ "TX_GONZALES_AND", "TX Gonzales CAD" },
			{ "TX_GRAY_AND", "TX Gray CAD" },
			{ "TX_GRAYSON_AND", "TX Grayson CAD" },
			{ "TX_GREGG_AND", "TX Gregg CAD" },
			{ "TX_GRIMES_AND", "TX Grimes CAD" },
			{ "TX_GUADALUPE_AND", "TX Guadalupe CAD" },
			{ "TX_HALE_AND", "TX Hale CAD" }, { "TX_HALL_AND", "TX Hall CAD" },
			{ "TX_HAMILTON_AND", "TX Hamilton CAD" },
			{ "TX_HANSFORD_AND", "TX Hansford CAD" },
			{ "TX_HARDEMAN_AND", "TX Hardeman CAD" },
			{ "TX_HARDIN_AND", "TX Hardin CAD" },
			{ "TX_HARRIS_AND", "TX Harris CAD" },
			{ "TX_HARRISON_AND", "TX Harrison CAD" },
			{ "TX_HARTLEY_AND", "TX Hartley CAD" },
			{ "TX_HASKELL_AND", "TX Haskell CAD" },
			{ "TX_HAYS_AND", "TX Hays CAD" },
			{ "TX_HEMPHILL_AND", "TX Hemphill CAD" },
			{ "TX_HENDERSON_AND", "TX Henderson CAD" },
			{ "TX_HIDALGO_AND", "TX Hidalgo CAD" },
			{ "TX_HILL_AND", "TX Hill CAD" },
			{ "TX_HOCKLEY_AND", "TX Hockley CAD" },
			{ "TX_HOOD_AND", "TX Hood CAD" },
			{ "TX_HOPKINS_AND", "TX Hopkins CAD" },
			{ "TX_HOUSTON_AND", "TX Houston CAD" },
			{ "TX_HOWARD_AND", "TX Howard CAD" },
			{ "TX_HUDSPETH_AND", "TX Hudspeth CAD" },
			{ "TX_HUNT_AND", "TX Hunt CAD" },
			{ "TX_HUTCHINSON_AND", "TX Hutchinson CAD" },
			{ "TX_IRION_AND", "TX Irion CAD" },
			{ "TX_JACK_AND", "TX Jack CAD" },
			{ "TX_JACKSON_AND", "TX Jackson CAD" },
			{ "TX_JASPER_AND", "TX Jasper CAD" },
			{ "TX_JEFF_DAVIS_AND", "TX Jeff Davis CAD" },
			{ "TX_JEFFERSON_AND", "TX Jefferson CAD" },
			{ "TX_JIM_HOGG_AND", "TX Jim Hogg CAD" },
			{ "TX_JIM_WELLS_AND", "TX Jim Wells CAD" },
			{ "TX_JOHNSON_AND", "TX Johnson CAD" },
			{ "TX_JONES_AND", "TX Jones CAD" },
			{ "TX_KARNES_AND", "TX Karnes CAD" },
			{ "TX_KAUFMAN_AND", "TX Kaufman CAD" },
			{ "TX_KENDALL_AND", "TX Kendall CAD" },
			{ "TX_KENEDY_AND", "TX Kenedy CAD" },
			{ "TX_KENT_AND", "TX Kent CAD" }, { "TX_KERR_AND", "TX Kerr CAD" },
			{ "TX_KIMBLE_AND", "TX Kimble CAD" },
			{ "TX_KING_AND", "TX King CAD" },
			{ "TX_KINNEY_AND", "TX Kinney CAD" },
			{ "TX_KLEBERG_AND", "TX Kleberg CAD" },
			{ "TX_KNOX_AND", "TX Knox CAD" },
			{ "TX_LA_SALLE_AND", "TX La Salle CAD" },
			{ "TX_LAMAR_AND", "TX Lamar CAD" },
			{ "TX_LAMB_AND", "TX Lamb CAD" },
			{ "TX_LAMPASAS_AND", "TX Lampasas CAD" },
			{ "TX_LAVACA_AND", "TX Lavaca CAD" },
			{ "TX_LEE_AND", "TX Lee CAD" }, { "TX_LEON_AND", "TX Leon CAD" },
			{ "TX_LIBERTY_AND", "TX Liberty CAD" },
			{ "TX_LIMESTONE_AND", "TX Limestone CAD" },
			{ "TX_LIPSCOMB_AND", "TX Lipscomb CAD" },
			{ "TX_LIVE_OAK_AND", "TX Live Oak CAD" },
			{ "TX_LLANO_AND", "TX Llano CAD" },
			{ "TX_LOVING_AND", "TX Loving CAD" },
			{ "TX_LUBBOCK_AND", "TX Lubbock CAD" },
			{ "TX_LYNN_AND", "TX Lynn CAD" },
			{ "TX_MADISON_AND", "TX Madison CAD" },
			{ "TX_MARION_AND", "TX Marion CAD" },
			{ "TX_MARTIN_AND", "TX Martin CAD" },
			{ "TX_MASON_AND", "TX Mason CAD" },
			{ "TX_MATAGORDA_AND", "TX Matagorda CAD" },
			{ "TX_MAVERICK_AND", "TX Maverick CAD" },
			{ "TX_MCCULLOCH_AND", "TX McCulloch CAD" },
			{ "TX_MCLENNAN_AND", "TX McLennan CAD" },
			{ "TX_MCMULLEN_AND", "TX McMullen CAD" },
			{ "TX_MEDINA_AND", "TX Medina CAD" },
			{ "TX_MENARD_AND", "TX Menard CAD" },
			{ "TX_MIDLAND_AND", "TX Midland CAD" },
			{ "TX_MILAM_AND", "TX Milam CAD" },
			{ "TX_MILLS_AND", "TX Mills CAD" },
			{ "TX_MITCHELL_AND", "TX Mitchell CAD" },
			{ "TX_MONTAGUE_AND", "TX Montague CAD" },
			{ "TX_MONTGOMERY_AND", "TX Montgomery CAD" },
			{ "TX_MOORE_AND", "TX Moore CAD" },
			{ "TX_MORRIS_AND", "TX Morris CAD" },
			{ "tx_motley_and", "TX Motley CAD" },
			{ "TX_NACOGDOCHES_AND", "TX Nacogdoches CAD" },
			{ "TX_NAVARRO_AND", "TX Navarro CAD" },
			{ "TX_NEWTON_AND", "TX Newton CAD" },
			{ "TX_NOLAN_AND", "TX Nolan CAD" },
			{ "TX_NUECES_AND", "TX Nueces CAD" },
			{ "TX_OCHILTREE_AND", "TX Ochiltree CAD" },
			{ "TX_OLDHAM_AND", "TX Oldham CAD" },
			{ "TX_ORANGE_AND", "TX Orange CAD" },
			{ "TX_PALO_PINTO_AND", "TX Palo Pinto CAD" },
			{ "TX_PANOLA_AND", "TX Panola CAD" },
			{ "TX_PARKER_AND", "TX Parker CAD" },
			{ "TX_PARMER_AND", "TX Parmer CAD" },
			{ "TX_PECOS_AND", "TX Pecos CAD" },
			{ "TX_POLK_AND", "TX Polk CAD" },
			{ "TX_POTTER_AND", "TX Potter CAD" },
			{ "TX_PRESIDIO_AND", "TX Presidio CAD" },
			{ "TX_RAINS_AND", "TX Rains CAD" },
			{ "TX_RANDALL_AND", "TX Randall CAD" },
			{ "TX_REAGAN_AND", "TX Reagan CAD" },
			{ "TX_REAL_AND", "TX Real CAD" },
			{ "TX_RED_RIVER_AND", "TX Red River CAD" },
			{ "TX_REEVES_AND", "TX Reeves CAD" },
			{ "TX_REFUGIO_AND", "TX Refugio CAD" },
			{ "TX_ROBERTS_AND", "TX Roberts CAD" },
			{ "TX_ROBERTSON_AND", "TX Robertson CAD" },
			{ "TX_ROCKWALL_AND", "TX Rockwall CAD" },
			{ "TX_RUNNELS_AND", "TX Runnels CAD" },
			{ "TX_RUSK_AND", "TX Rusk CAD" },
			{ "TX_SABINE_AND", "TX Sabine CAD" },
			{ "TX_SAN_AUGUSTINE_AND", "TX San Augustine CAD" },
			{ "TX_SAN_JACINTO_AND", "TX San Jacinto CAD" },
			{ "TX_SAN_PATRICIO_AND", "TX San Patricio CAD" },
			{ "TX_SAN_SABA_AND", "TX San Saba CAD" },
			{ "TX_SCHLEICHER_AND", "TX Schleicher CAD" },
			{ "TX_SCURRY_AND", "TX Scurry CAD" },
			{ "TX_SHACKELFORD_AND", "TX Shackelford CAD" },
			{ "TX_SHELBY_AND", "TX Shelby CAD" },
			{ "TX_SHERMAN_AND", "TX Sherman CAD" },
			{ "TX_SMITH_AND", "TX Smith CAD" },
			{ "TX_SOMERVELL_AND", "TX Somervell CAD" },
			{ "TX_STARR_AND", "TX Starr CAD" },
			{ "TX_STEPHENS_AND", "TX Stephens CAD" },
			{ "TX_STERLING_AND", "TX Sterling CAD" },
			{ "TX_STONEWALL_AND", "TX Stonewall CAD" },
			{ "TX_SUTTON_AND", "TX Sutton CAD" },
			{ "TX_SWISHER_AND", "TX Swisher CAD" },
			{ "TX_TARRANT_AND", "TX Tarrant CAD" },
			{ "TX_TAYLOR_AND", "TX Taylor CAD" },
			{ "TX_TERRELL_AND", "TX Terrell CAD" },
			{ "TX_TERRY_AND", "TX Terry CAD" },
			{ "TX_THROCKMORTON_AND", "TX Throckmorton CAD" },
			{ "TX_TITUS_AND", "TX Titus CAD" },
			{ "TX_TOM_GREEN_AND", "TX Tom Green CAD" },
			{ "TX_TRAVIS_AND", "TX Travis CAD" },
			{ "TX_TRINITY_AND", "TX Trinity CAD" },
			{ "TX_TYLER_AND", "TX Tyler CAD" },
			{ "TX_UPSHUR_AND", "TX Upshur CAD" },
			{ "TX_UPTON_AND", "TX Upton CAD" },
			{ "TX_UVALDE_AND", "TX Uvalde CAD" },
			{ "TX_VAL_VERDE_AND", "TX Val Verde CAD" },
			{ "TX_VAN_ZANDT_AND", "TX Van Zandt CAD" },
			{ "TX_VICTORIA_AND", "TX Victoria CAD" },
			{ "TX_WALKER_AND", "TX Walker CAD" },
			{ "TX_WALLER_AND", "TX Waller CAD" },
			{ "TX_WARD_AND", "TX Ward CAD" },
			{ "TX_WASHINGTON_AND", "TX Washington CAD" },
			{ "TX_WEBB_AND", "TX Webb CAD" },
			{ "TX_WHARTON_AND", "TX Wharton CAD" },
			{ "TX_WHEELER_AND", "TX Wheeler CAD" },
			{ "TX_WICHITA_AND", "TX Wichita CAD" },
			{ "TX_WILBARGER_AND", "TX Wilbarger CAD" },
			{ "TX_WILLACY_AND", "TX Willacy CAD" },
			{ "TX_WILLIAMSON_AND", "TX Williamson CAD" },
			{ "TX_WILSON_AND", "TX Wilson CAD" },
			{ "TX_WINKLER_AND", "TX Winkler CAD" },
			{ "TX_WISE_AND", "TX Wise CAD" }, { "TX_WOOD_AND", "TX Wood CAD" },
			{ "TX_YOAKUM_AND", "TX Yoakum CAD" },
			{ "TX_YOUNG_AND", "TX Young CAD" },
			{ "TX_ZAPATA_AND", "TX Zapata CAD" },
			{ "TX_ZAVALA_AND", "TX Zavala CAD" } };

	// DMV
	public static List<String[][]> listOfOptions_DMV = new ArrayList<String[][]>();
	public static List<String[][]> listOfOptions_DMV_DPPA = new ArrayList<String[][]>();

	public static String[][] DMV_PLATE_OPTIONS = {
			{ "GRP_DMV_PLATE", "Search All Items Below" },
			{ "CODMV", "Colorado DMV" }, { "FLDMV", "Florida DMV [Old]" },
			{ "IDDMV", "Idaho DMV [old]" }, { "MEDMV", "Maine DMV [old]" },
			{ "MNDMV", "Minnesota DMV" }, { "MSDMV", "Mississippi DMV" },
			{ "MODMV", "Missouri DMV [old]" },
			{ "NCDMV", "North Carolina DMV" }, { "OHDMV", "Ohio DMV [old]" },
			{ "ORDMV", "Oregon DMV [old]" },
			{ "SDDMV", "South Dakota DMV [old]" },
			{ "TNDMV", "Tennessee DMV [old]" }, { "TXDMV", "Texas DMV" },
			{ "UTDMV", "Utah DMV [old]" }, { "WVDMV", "West Virginia DMV" },
			{ "WIDMV", "Wisconsin DMV" },
			{ "WIDMV_USED", "Wisconsin DMV [Used]" } };

	public static String[][] DMV_VIN_OPTIONS = {
			{ "GRP_DMV_VIN", "Search All Items Below" },
			{ "CODMV", "Colorado DMV" }, { "FLDMV", "Florida DMV [Old]" },
			{ "IDDMV", "Idaho DMV [old]" }, { "IADMV", "Iowa DMV" },
			{ "KYDMV", "Kentucky DMV - [Old]" },
			{ "MEDMV", "Maine DMV [old]" }, { "MNDMV", "Minnesota DMV" },
			{ "MSDMV", "Mississippi DMV" }, { "MODMV", "Missouri DMV [old]" },
			{ "NEDMV", "Nebraska DMV" }, { "NCDMV", "North Carolina DMV" },
			{ "OHDMV", "Ohio DMV [old]" }, { "ORDMV", "Oregon DMV [old]" },
			{ "TNDMV", "Tennessee DMV [old]" }, { "TXDMV", "Texas DMV" },
			{ "UTDMV", "Utah DMV [old]" }, { "WVDMV", "West Virginia DMV" },
			{ "WIDMV", "Wisconsin DMV" },
			{ "WIDMV_USED", "Wisconsin DMV [Used]" },
			{ "WYDMV", "Wyoming DMV" } };

	/*
	 * private static String ALABAMA_PROFESSIONAL_LICENSE = { {
	 * "GRP_PL_AL_NAME", "Search All Items Below" }, { "AL_PRO_ABOR_REP_CNTR",
	 * "Alabama Abortion Or Reproductive Health Centers" }, { "AL_PRO_ACCTFRM",
	 * "Alabama Accountant Firms" }, { "AL_PRO_ACCTS", "Alabama Accountants" },
	 * { "AL_PRO_AMBU_SURG", "Alabama Ambulatory Surgical Treatment Facilities"
	 * }, { "AL_PRO_AMBU_SURG_EYE",
	 * "Alabama Ambulatory Surgical Treatment Facilities - Eye" }, {
	 * "AL_PRO_ANES_ASST", "Alabama Anesthesiologist Assistants" }, {
	 * "AL_PRO_ARCH", "Alabama Architects" }, { "AL_PRO_ATTY",
	 * "Alabama Attorneys" }, { "AL_PRO_AUCTION", "Alabama Auctioneers" }, {
	 * "AL_PRO_BANKS", "Alabama Banks" }, { "AL_PRO_BLOOD_BANK",
	 * "Alabama Blood Banks" }, { "AL_PRO_CEREBRAL_PAL",
	 * "Alabama Cerebral Palsy Treatment Centers" }, { "AL_PRO_CHIROPRACTORS",
	 * "Alabama Chiropractors" }, { "AL_PRO_COMM_MENT_CTR",
	 * "Alabama Community Mental Health Centers" }, { "AL_PRO_CONG_ASST_LIV",
	 * "Alabama Congregate Assisted Living Facilities" }, {
	 * "AL_PRO_CONG_SPEC_LIV",
	 * "Alabama Congregate Specialty Care Assisted Living Facilities" }, {
	 * "AL_PRO_CONSUMER_CRED", "Alabama Consumer Credit Finance Companies" }, {
	 * "AL_PRO_CRIT_ACC_HOSP", "Alabama Critical Access Hospitals" }, {
	 * "AL_PRO_DEFERRED_PRES", "Alabama Deferred Presentment" }, {
	 * "AL_PRO_DENTAL_HYGIEN", "Alabama Dental Hygienists" }, {
	 * "AL_PRO_DENTIST", "Alabama Dentists" }, { "AL_PRO_DIETITIAN",
	 * "Alabama Dietitians" }, { "AL_PRO_ELEC_CONT",
	 * "Alabama Electrical Contractors" }, { "AL_PRO_ELEC_CONT_LV",
	 * "Alabama Electrical Contractors - Low Voltage" }, {
	 * "AL_PRO_ELEC_CONT_RES", "Alabama Electrical Contractors - Residential" },
	 * { "AL_PRO_ELEC_CONT_SIG", "Alabama Electrical Contractors - Sign" }, {
	 * "AL_PRO_END_RENAL_CTR",
	 * "Alabama End Stage Renal Disease Treatment Centers" }, {
	 * "AL_PRO_ENGR_INTERN", "Alabama Engineer Interns" }, {
	 * "AL_PRO_ENGR_SURVEY", "Alabama Engineering/Surveying Firms" }, {
	 * "AL_PRO_FAM_ASST_LIV", "Alabama Family Assisted Living Facilities" }, {
	 * "AL_PRO_FED_QUAL_HLTH", "Alabama Federally Qualified Health Centers" }, {
	 * "AL_PRO_GEN_CONT", "Alabama General Contractors" }, {
	 * "AL_PRO_GENR_HOSPITAL", "Alabama General Hospitals" }, {
	 * "AL_PRO_GEOLOGIST", "Alabama Geologists" }, { "AL_PRO_GRP_ASST_LIV",
	 * "Alabama Group Assisted Living Facilities" }, { "AL_PRO_GRP_SPEC_LIV",
	 * "Alabama Group Specialty Care Assisted Living Facilities" }, {
	 * "AL_PRO_HEAT_AC_CONT", "Alabama Heating and A/C Contractors" }, {
	 * "AL_PRO_HOME_BUILD", "Alabama Home Builders" }, { "AL_PRO_HOME_HLTH_AGC",
	 * "Alabama Home Health Agencies" }, { "AL_PRO_HOME_INSPECT",
	 * "Alabama Home Inspectors" }, { "AL_PRO_IN_HOME_HOSPI",
	 * "Alabama In-Home Hospices" }, { "AL_PRO_IN_PAT_HOSPIC",
	 * "Alabama In-Patient Hospices" }, { "AL_PRO_IND_CLIN_LAB",
	 * "Alabama Independent Clinical Laboratories" }, { "AL_PRO_IND_PHYS_LAB",
	 * "Alabama Independent Physiological Laboratories" }, {
	 * "AL_PRO_INSU_ADJUST", "Alabama Insurance" }, { "AL_PRO_INSU_AGT_TITL",
	 * "Alabama Insurance Agents" }, { "AL_PRO_INSU_CO",
	 * "Alabama Insurance Companies" }, { "AL_PRO_INTER_DESIGN",
	 * "Alabama Interior Designers" }, { "AL_PRO_INT_FAC_MENTL",
	 * "Alabama Intermediate Care Facilities For The Mentally Retarded" }, {
	 * "AL_PRO_LAND_ARCH", "Alabama Landscape Architects" }, {
	 * "AL_PRO_LAND_SURV_INT", "Alabama Land Surveyor Interns" }, {
	 * "AL_PRO_LIM_PHYSICIAN", "Alabama Limited Physicians" }, {
	 * "AL_PRO_MARRIAGE_THER", "Alabama Marriage Therapy" }, {
	 * "AL_PRO_MORTGAGE_BROK", "Alabama Mortgage Brokers" }, { "AL_PRO_NOTARY",
	 * "Alabama Notaries" }, { "AL_PRO_NURSING_FACIL",
	 * "Alabama Nursing Facilities" }, { "AL_PRO_NURS_HOME_ADM",
	 * "Alabama Nursing Home Administrators" }, { "AL_PRO_OPTOM",
	 * "Alabama Optometrists" }, { "AL_PRO_PAWN_SHOP", "Alabama Pawn Shops" }, {
	 * "AL_PRO_PHYS_THER", "Alabama Physical Therapists" }, {
	 * "AL_PRO_PHYS_ASST", "Alabama Physician Assistants" }, {
	 * "AL_PRO_PHYSICIAN", "Alabama Physicians" }, { "AL_PRO_PLUMB_GAS",
	 * "Alabama Plumbers and Gas Fitters" }, { "AL_PRO_PORT_XRAY_SUP",
	 * "Alabama Portable X-Ray Suppliers" }, { "AL_PRO_PRO_ENGR",
	 * "Alabama Professional Engineers" }, { "AL_PRO_PRO_LAND_SRV",
	 * "Alabama Professional Land Surveyors" }, { "AL_PRO_REAL_EST_APPR",
	 * "Alabama Real Estate Appraisers" }, { "al_pro_real_brokge",
	 * "Alabama Real Estate Brokerages" }, { "AL_PRO_REAL_BROK",
	 * "Alabama Real Estate Brokers" }, { "AL_PRO_REHAB_CENTER",
	 * "Alabama Rehabilitation Centers" }, { "AL_PRO_REINS_INTER",
	 * "Alabama Reinsurance Intermediaries" }, { "AL_PRO_RES_TREAT_FAC",
	 * "Alabama Residential Treatment Facilities" }, { "AL_PRO_RURAL_HEALTH",
	 * "Alabama Rural Health Clinics" }, { "AL_PRO_SKIL_NURS_FAC",
	 * "Alabama Skilled Nursing Facilities" }, { "AL_PRO_SLEEP_DIS_CTR",
	 * "Alabama Sleep Disorders Centers" }, { "AL_PRO_SMALL_LOAN",
	 * "Alabama Small Loans" }, { "AL_PRO_SOCIAL_WRK", "Alabama Social Workers"
	 * }, { "AL_PRO_SPEC_LTC_HOSP",
	 * "Alabama Specialized Long Term Care Hospitals" }, {
	 * "AL_PRO_SPEC_PED_HOSP", "Alabama Specialized Pediatric Hospitals" }, {
	 * "AL_PRO_SPEC_PSY_HOSP", "Alabama Specialized Psychiatric Hospitals" }, {
	 * "AL_PRO_SPEC_REH_HOSP", "Alabama Specialized Rehabilitation Hospitals" },
	 * { "AL_PRO_SPEC_COLL_STA", "Alabama Specimen Collection Stations" }, {
	 * "AL_PRO_SPORTS", "Alabama Sports Agents" }, { "AL_PRO_UNLIC_FACILIT",
	 * "Alabama Unlicensed Facilities" }, { "AL_PRO_WATER_PRO",
	 * "Alabama Wastewater Professionals" } };
	 */
	protected static final Category logger = Logger
			.getLogger(XXGenericPublicDataParentSiteConfiguration.class);

	static {
		listOfOptions_DMV.add(DMV_PLATE_OPTIONS);
		listOfOptions_DMV.add(DMV_VIN_OPTIONS);
		listOfOptions_DMV_DPPA.add(DPPA);

		String texasFilterRegEx = "(?is)(.*_TX_.*)|(\\Atx.*)";

		listOfOptions_state
				.add(filterOutOptions(
						XXGenericPublicDataParentSiteConfiguration.CIVIL_COURT_NAME_SEARCH_OPTIONS,
						texasFilterRegEx));
		listOfOptions_state
				.add(filterOutOptions(
						XXGenericPublicDataParentSiteConfiguration.MOST_WANTED_NAME_SEARCH_OPTIONS,
						texasFilterRegEx));
		listOfOptions_state
				.add(filterOutOptions(
						XXGenericPublicDataParentSiteConfiguration.SEX_OFFENDER_NAME_SEARCH_OPTIONS,
						texasFilterRegEx));
		listOfOptions_state
				.add(filterOutOptions(
						XXGenericPublicDataParentSiteConfiguration.CRIMINAL_NAME_SEARCH_OPTIONS,
						texasFilterRegEx));
		listOfOptions_state
				.add(filterOutOptions(
						XXGenericPublicDataParentSiteConfiguration.TERRORISM_NAME_SEARCH_OPTIONS,
						texasFilterRegEx));
		listOfOptions_state
				.add(filterOutOptions(
						XXGenericPublicDataParentSiteConfiguration.VOTER_NAME_SEARCH_OPTIONS,
						texasFilterRegEx));
		listOfOptions_state
				.add(filterOutOptions(
						XXGenericPublicDataParentSiteConfiguration.DRIVERS_LICENCE_NAME_SEARCH_OPTIONS,
						texasFilterRegEx));
		listOfOptions_state
				.add(filterOutOptions(
						XXGenericPublicDataParentSiteConfiguration.SECRETARY_OF_STATE_CORPORATION_NAME_SEARCH,
						texasFilterRegEx));
		listOfOptions_state
				.add(filterOutOptions(
						XXGenericPublicDataParentSiteConfiguration.PROFESSIONAL_LICENSE_NAME_SEARCH_OPTIONS,
						texasFilterRegEx));
		listOfOptions_state
				.add(filterOutOptions(
						XXGenericPublicDataParentSiteConfiguration.TAX_SEARCH_NAME_SEARCH_OPTIONS,
						texasFilterRegEx));

		// just 4 texas
		listOfOptions_county.add(CIVIL_COURT_NAME_SEARCH_TX);
		listOfOptions_county.add(SEX_OFFENDER_NAME_SEARCH_TX);
		listOfOptions_county.add(CRIMINAL_NAME_SEARCH_TX);
		listOfOptions_county.add(PROFESSIONAL_LICENSE_NAME_SEARCH_TX);
		listOfOptions_county.add(VOTER_NAME_SEARCH_TX);
		listOfOptions_county.add(TAX_SEARCH_NAME_SEARCH_TX);
		listOfOptions_county.add(DPPA);
	}

	public static List<String[][]> filterOutOptions(String regEXForRuleOut) {
		List<String[][]> filteredListOfOptions = new ArrayList<String[][]>();
		for (String[][] matrix : listOfOptions_state) {
			for (int i = 0; i < matrix.length; i++) {
				String value = matrix[i][0];
				if (value.matches(regEXForRuleOut) || i == 0) {
					filteredListOfOptions.add(new String[][] { { matrix[i][0],
							matrix[i][1] } });
				}
			}
		}
		return filteredListOfOptions;
	}

	public static String[][] filterOutOptions(String[][] matrix,
			String regEXForRuleOut) {
		if (StringUtils.isEmpty(regEXForRuleOut))
			return matrix;

		List<String[][]> filteredListOfOptions = new ArrayList<String[][]>();
		for (int i = 0; i < matrix.length; i++) {
			String value = matrix[i][0];
			if (value.matches(regEXForRuleOut) || i == 0) {
				filteredListOfOptions.add(new String[][] { { matrix[i][0],
						matrix[i][1] } });
			}
		}
		String[][] returnMatrix = new String[filteredListOfOptions.size()][2];
		int i = 0;
		for (String[][] strings : filteredListOfOptions) {
			returnMatrix[i] = strings[0];
			i++;
		}
		return returnMatrix;
	}

}
